### ISSUE TITLE
Annoying message while using OpenTelemetry: msg: defaulted common supertype for type <...> due to err:java.lang.IllegalStateException: ClassLoader is null?

### ISSUE THREAD

**Issue by dmitryb-dev** [ebean-orm/ebean#2687] opened 2022-05-11 12:33 UTC
I'm getting a lot of messages like this:

`ebean-enhance> cls: io/opentelemetry/javaagent/shaded/io/opentelemetry/context/LazyStorage  msg: defaulted common supertype for type1:io/opentelemetry/javaagent/shaded/io/opentelemetry/context/StrictContextStorage type2:io/opentelemetry/javaagent/shaded/io/opentelemetry/context/ContextStorage due to err:java.lang.IllegalStateException: ClassLoader is null?`

Probably `io.opentelemetry` should be added to [IgnoreClassHelper.java](https://github.com/ebean-orm/ebean-agent/blob/9cf813d9eae63cab4b0e77f255bd752d5821fdb0/ebean-agent/src/main/java/io/ebean/enhance/common/IgnoreClassHelper.java)?

**Comment by rbygrave** [comment] 2022-05-13 00:39
Well, yes we could and probably should add `io.opentelemetry` to the ignore list - but note that is just a performance feature (ignoring packages that we reasonably know should never contain entity beans, query beans or transactional methods).

It would be good to try and reproduce this issue first it we can. That is, the `ClassLoader is null?` part more suggests this is more a bug. 

Are you able to create a test case?  Perhaps a Fork/PR of https://github.com/ebean-orm-examples/example-minimal ?  

I am unable to reproduce by for example, adding dependency opentelemetry-sdk and code `OpenTelemetrySdk openTelemetrySdk = OpenTelemetrySdk.builder().buildAndRegisterGlobal();` 

... makes we wonder if there is something interesting with the opentelemetry agent.

**Comment by rbygrave** [comment] 2022-05-13 05:03
Refer to: https://github.com/ebean-orm/ebean-agent/issues/183

**Comment by rbygrave** [comment] 2022-05-16 00:39
Ok, I'll close this for now as fixed in 13.6.1 with ebean-agent ignoring `io.opentelemetry`.  

If we can get a test case that reproduces with the `ClassLoader is null?` error we can reopen or create a new one and look at that.

**Closed by rbygrave** 2022-05-16 00:39 UTC
