### ISSUE TITLE
MySQLSyntaxErrorException when update in bulk using idIn() expression

### ISSUE THREAD

**Issue by sizer** [ebean-orm/ebean#1996] opened 2020-04-23 12:47 UTC
I can NOT update in bulk ;(
Is it bug?? It may miss alias for table as ‘t0’.

#### Environments

Java@8
ebean@12.2.4
mysql-connector-java@5.1.44

#### Code

`Archive` is a model extended `io.ebean.Model`.

```java
Archive.find.query().where().idIn(1, 2).asUpdate().set("data", "foo").update();

```

#### Error

```
Exception in thread "main" javax.persistence.PersistenceException: Query threw SQLException:Unknown column 't0.id' in 'where clause' Bind values:["foo",Array[2]={1,2}] Query was:update archive set data=? where t0.id in (?,?)
	at io.ebean.config.dbplatform.SqlCodeTranslator.translate(SqlCodeTranslator.java:55)
	at io.ebean.config.dbplatform.DatabasePlatform.translate(DatabasePlatform.java:231)
	at io.ebeaninternal.server.query.CQueryEngine.translate(CQueryEngine.java:149)
	at io.ebeaninternal.server.query.CQueryEngine.executeUpdate(CQueryEngine.java:93)
	at io.ebeaninternal.server.query.CQueryEngine.update(CQueryEngine.java:77)
	at io.ebeaninternal.server.query.DefaultOrmQueryEngine.update(DefaultOrmQueryEngine.java:76)
	at io.ebeaninternal.server.core.OrmQueryRequest.update(OrmQueryRequest.java:408)
	at io.ebeaninternal.server.core.DefaultServer.update(DefaultServer.java:1418)
	at io.ebeaninternal.server.querydefn.DefaultOrmQuery.update(DefaultOrmQuery.java:1478)
	at io.ebeaninternal.server.querydefn.DefaultUpdateQuery.update(DefaultUpdateQuery.java:64)
	at example.Hello.main(Hello.java:9)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 't0.id' in 'where clause'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2487)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at io.ebean.datasource.pool.ExtendedPreparedStatement.executeUpdate(ExtendedPreparedStatement.java:138)
	at io.ebeaninternal.server.query.CQueryUpdate.execute(CQueryUpdate.java:92)
	at io.ebeaninternal.server.query.CQueryEngine.executeUpdate(CQueryEngine.java:82)
	... 7 more
```

#### Sample

https://github.com/rms-shinse/hello-ebean/tree/feature/updateWithWhere

**Comment by rbygrave** [comment] 2020-04-28 09:23
This does not reproduce, it all works as expected. 
It looks like you are using an old version of ebean.

```java
  @Test
  public void query_asUpdate_idIn() {

    ResetBasicData.reset();

    LoggedSqlCollector.start();

    int rows = server().find(Customer.class)
      .where()
      .in("id", 1000, 1001, 1002)
      .asUpdate()
      .setRaw("status = ?", "A")
      .setLabel("asUpdate")
      .update();


    List<String> sql = LoggedSqlCollector.stop();
    assertThat(sql).hasSize(1);
    assertThat(rows).isEqualTo(0);

    assertSql(sql.get(0)).contains("update o_customer set status = ? where id in (?,?,?)");
  }
```
```logs
21:19:32.734 [main] DEBUG io.ebean.SQL - txn[1002] update o_customer set status = ? where id in (?,?,?); --bind(A,Array[3]={1000,1001,1002}) rows:0
21:19:32.735 [main] DEBUG io.ebean.TXN - txn[1002] Commit
```
Running this test against mysql 8.

**Comment by rbygrave** [comment] 2020-04-28 09:27
Git pushed to master the above commit that closely matches your update example.

Awaiting more information but your sample build.sbt has ` libraryDependencies += "io.ebean" % "ebean" % "11.45.1",` so maybe you need to update the version of ebean.

Note that you can also run ebean by itself (without playframework) via the minimal example - https://github.com/ebean-orm-examples/example-minimal

**Comment by sizer** [comment] 2020-04-29 08:37
@rbygrave 
you can reproduce by this implementation 👍 

> ```diff
> -       .in("id", 1000, 1001, 1002)
> +       .idIn(1000, 1001, 1002)
> ```
> https://github.com/sizer/ebean/pull/1

### log

```
javax.persistence.PersistenceException: Query threw SQLException:列 "T0.ID" が見つかりません
Column "T0.ID" not found; SQL statement:
update o_customer set status = ? where t0.id in (?,?,?,?,?) [42122-199] Bind values:[null] Query was:update o_customer set status = ? where t0.id in (?,?,?,?,?)

```

**Comment by rbygrave** [comment] 2020-04-30 09:34
Ok, now fixed with that last commit there.

**Closed by rbygrave** 2020-04-30 09:34 UTC
Labels: bug
