### ISSUE TITLE
PersistenceException while using aggregate query on related entity

### ISSUE THREAD

**Issue by shubhamp-zeotap** [ebean-orm/ebean#1737] opened 2019-06-27 23:22 UTC
## Actual Bevahiour

@rbygrave Hi Rob, as discussed with you [here](https://github.com/ebean-orm/ebean/issues/1408), Ebean is generating PersistenceException when aggregation is done on an entity type field.

These are two actual models I am using

```
@Data
@Entity
@Table(name = "segments")
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@AllArgsConstructor @NoArgsConstructor
public class PartialSegment extends Model {

    @Id
    @Column(name = "id")
    private Long id;

    @NotNull
    @Index
    @Column(name = "segment_id_zat")
    private Long segmentIdZat;

    @Index
    @ManyToOne
    @JoinColumn(name = "segment_status_id", referencedColumnName = "status_id", nullable = false)
    private SegmentStatus status;

    public static final Finder<Long, Segment> find = new Finder<Long, Segment>(Segment.class);
}
```

Status Model:
```
@Data
@Entity
@Table(name = "segment_status")
@Cache(enableQueryCache = true)
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@AllArgsConstructor @NoArgsConstructor
public class SegmentStatus extends Model {

    @Id
    @Column(name = "status_id")
    private Long statusId;

    @NotNull
    @Column(name = "status")
    private String status;

    @DbArray
    @Column(name = "country_ids")
    private List<Long> countryIds;

    public static final Finder<Long, SegmentStatus> find = new Finder<Long, SegmentStatus>(SegmentStatus.class);

}
```

I am trying to execute the following query using Ebean aggregation features:
```
        List<PartialSegment> segments = Ebean.find(PartialSegment.class)
                .select("segmentIdZat, min(status)")
                .where().eq("segmentIdZat", 108L).findList();
```

The query generated by this is perfectly fine where Ebean was able to resolve status entity to its column. This is it.

```
[debug] io.ebean.SQL - txn[1001] select t0.segment_id_zat, min(t0.segment_status_id) from segments t0 where t0.segment_id_zat = ?  group by t0.segment_id_zat; --bind(108)
```

This is the stack trace of the error:

```
javax.persistence.PersistenceException: Error loading on min(status)
	at io.ebeaninternal.server.deploy.DynamicPropertyAggregationFormula.load(DynamicPropertyAggregationFormula.java:49)
	at io.ebeaninternal.server.query.SqlTreeNodeBean.load(SqlTreeNodeBean.java:288)
	at io.ebeaninternal.server.query.CQuery.readNextBean(CQuery.java:455)
	at io.ebeaninternal.server.query.CQuery.hasNext(CQuery.java:543)
	at io.ebeaninternal.server.query.CQuery.readCollection(CQuery.java:574)
	at io.ebeaninternal.server.query.CQueryEngine.findMany(CQueryEngine.java:385)
	at io.ebeaninternal.server.query.DefaultOrmQueryEngine.findMany(DefaultOrmQueryEngine.java:156)
	at io.ebeaninternal.server.core.OrmQueryRequest.findList(OrmQueryRequest.java:442)
	at io.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1516)
	at io.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1494)
	at io.ebeaninternal.server.querydefn.DefaultOrmQuery.findList(DefaultOrmQuery.java:1433)
	at io.ebeaninternal.server.expression.DefaultExpressionList.findList(DefaultExpressionList.java:404)
	at services.SegmentListingService.listSegments(SegmentListingService.java:32)
	at controllers.SegmentControllerV2.listSegments(SegmentControllerV2.java:65)
	at v2.Routes$$anonfun$routes$1.$anonfun$applyOrElse$4(Routes.scala:95)
	at play.core.routing.HandlerInvokerFactory$$anon$7.resultCall(HandlerInvoker.scala:146)
	at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$3$$anon$4$$anon$5.invocation(HandlerInvoker.scala:115)
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:111)
	at play.http.DefaultActionCreator$1.call(DefaultActionCreator.java:32)
	at actions.AuthorizedAccessAction.call(AuthorizedAccessAction.java:16)
	at actions.AuthenticatedAccessAction.call(AuthenticatedAccessAction.java:27)
	at play.core.j.JavaAction.$anonfun$apply$8(JavaAction.scala:170)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:653)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:287)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:64)
	at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:71)
	at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:56)

```

## Expected Behaviour

As the aggregation is done on the @Id column, would it possible to attach the complete SegmentStatus bean to PartialSegment model? Please also suggest the alternatives. I am basically expecting something like this for the result of query execution (this is the JSON representation of models):

```
{
  "segmentIdZat": 108,
  "status": {
    "statusId": 1,
    "status": "some value",
    "countryIds": ["some", "values"]
  }
}
```

Thanks for your help!

**Comment by rbygrave** [comment] 2019-06-27 23:35
Firstly excellent issue / bug report - perfect !!

Right so yes this is a bug.  We are doing a "dynamic aggregation" on a "foreign key column / property" (`min(t0.segment_status_id)`) ... and Ebean is failing to map that back to the `@ManyToOne` bean property.

> would it possible to attach the complete SegmentStatus bean to PartialSegment model?

Yes, once this is fixed we would likely just add a `fetchJoin("status")` to the query and I think that would be what we want (but yeah we need to fix this bug first).

>  Please also suggest the alternatives

Using `findNative()` would work ...  we should be able to have a findNative() query that also has `fetchJoin("status")` ... and get the same result in terms of the sql executed and graph built.

**Comment by shubhamp-zeotap** [comment] 2019-06-28 00:10
Thanks for the suggestion, Rob! But the thing is I am already using RawSql and findNative would only give me the advantage of auto column mapping in my case.

In my actual use case, the PartialSegment table would have more foreign entities and the SQL join would include around 7-8 more table except these (in a way very similar to this). Current RawSql SQL query has become very bulky and ugly to maintain that's why I wanted to shift to pure bean based access.

Any plans around when this will be fixed and made live? 

Thanks, Shubham

**Comment by rbygrave** [comment] 2019-06-28 03:19
Do you have the full stack trace?  The stack trace above is missing the "Caused by" part (which is important because I can't be sure I'm reproducing the issue plus it has important detail).

Can you tell me the version of Ebean you are using?

Thanks, Rob.

**Comment by rbygrave** [comment] 2019-06-28 09:10
So pushed the fix now.  For the fetchQuery scenario (the second commit):

## Query including fetchQuery

```java
    List<Contact> contacts = Ebean.find(Contact.class)
      .select("lastName, min(customer)")
      .fetchQuery("customer", "name, status")
      .findList();
```

The interesting part here is we support the "query join" using the `min(customer)` aggregation formula.  The resulting 2 sql queries are:
```sql
select t0.last_name, min(t0.customer_id) 
from contact t0 
group by t0.last_name

-- the query join ...
select t0.id, t0.name, t0.status from o_customer t0 
where ...
```

And the "query join" / "secondary query" can also have joins like:
```java
    List<Contact> contacts = Ebean.find(Contact.class)
      .select("lastName, min(customer)")
      .fetchQuery("customer", "name, status")
      .fetch("customer.billingAddress", "city, country")
      .findList();
``` 
and the secondary query then is:
```sql
select t0.id, t0.name, t0.status, t1.id, t1.city, t1.country_code 
from o_customer t0 
left join o_address t1 on t1.id = t0.billing_address_id  
where ...
``` 

So yup.  Done and closing.  I'll look to put out a release later tonight.

Cheers, Rob.

**Closed by rbygrave** 2019-06-28 09:10 UTC
Labels: bug

**Comment by shubhamp-zeotap** [comment] 2019-06-28 17:51
Hi Rob,

Thanks a lot for this and I apologize for the delayed response! 

This is all the stack trace available through e.printStackTrace() (earlier I included the stack trace from service to dao layer):

```
[info] play.api.Play - Application started (Dev)
2019-06-28 23:16:21 INFO  Version:21 - HV000001: Hibernate Validator 6.1.0.Alpha4
[debug] io.ebean.SQL - txn[1001] select t0.segment_id_zat, min(t0.segment_status_id) from segments t0 where t0.segment_id_zat = ?  group by t0.segment_id_zat; --bind(108)
class javax.persistence.PersistenceException
javax.persistence.PersistenceException: Error loading on min(status)
	at io.ebeaninternal.server.deploy.DynamicPropertyAggregationFormula.load(DynamicPropertyAggregationFormula.java:49)
	at io.ebeaninternal.server.query.SqlTreeNodeBean.load(SqlTreeNodeBean.java:288)
	at io.ebeaninternal.server.query.CQuery.readNextBean(CQuery.java:455)
	at io.ebeaninternal.server.query.CQuery.hasNext(CQuery.java:543)
	at io.ebeaninternal.server.query.CQuery.readCollection(CQuery.java:574)
	at io.ebeaninternal.server.query.CQueryEngine.findMany(CQueryEngine.java:385)
	at io.ebeaninternal.server.query.DefaultOrmQueryEngine.findMany(DefaultOrmQueryEngine.java:156)
	at io.ebeaninternal.server.core.OrmQueryRequest.findList(OrmQueryRequest.java:442)
	at io.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1516)
	at io.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1494)
	at io.ebeaninternal.server.querydefn.DefaultOrmQuery.findList(DefaultOrmQuery.java:1433)
	at io.ebeaninternal.server.expression.DefaultExpressionList.findList(DefaultExpressionList.java:404)
	at services.SegmentListingService.listSegments(SegmentListingService.java:31)
	at controllers.SegmentControllerV2.listSegments(SegmentControllerV2.java:65)
	at v2.Routes$$anonfun$routes$1.$anonfun$applyOrElse$4(Routes.scala:95)
	at play.core.routing.HandlerInvokerFactory$$anon$7.resultCall(HandlerInvoker.scala:146)
	at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$3$$anon$4$$anon$5.invocation(HandlerInvoker.scala:115)
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:111)
	at play.http.DefaultActionCreator$1.call(DefaultActionCreator.java:32)
	at actions.AuthorizedAccessAction.call(AuthorizedAccessAction.java:16)
	at actions.AuthenticatedAccessAction.call(AuthenticatedAccessAction.java:27)
	at play.core.j.JavaAction.$anonfun$apply$8(JavaAction.scala:170)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:653)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:287)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:64)
	at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:71)
	at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:56)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:68)
	at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete(Promise.scala:368)
	at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete$(Promise.scala:367)
	at scala.concurrent.impl.Promise$KeptPromise$Successful.onComplete(Promise.scala:375)
	at scala.concurrent.impl.Promise.transform(Promise.scala:29)
	at scala.concurrent.impl.Promise.transform$(Promise.scala:27)
	at scala.concurrent.impl.Promise$KeptPromise$Successful.transform(Promise.scala:375)
	at scala.concurrent.Future.map(Future.scala:287)
	at scala.concurrent.Future.map$(Future.scala:287)
	at scala.concurrent.impl.Promise$KeptPromise$Successful.map(Promise.scala:375)
	at scala.concurrent.Future$.apply(Future.scala:653)
	at play.core.j.JavaAction.apply(JavaAction.scala:171)
	at play.api.mvc.Action.$anonfun$apply$2(Action.scala:97)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:302)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.NullPointerException
	at io.ebeaninternal.server.deploy.DynamicPropertyAggregationFormula.load(DynamicPropertyAggregationFormula.java:43)
	... 58 more
```

I am using Ebean through Play Framework. These are the plugin versions I am using:

```
addSbtPlugin("com.typesafe.sbt" % "sbt-play-ebean" % "4.1.3")
addSbtPlugin("com.typesafe.sbt" % "sbt-play-enhancer" % "1.2.0")
```

This is importing package versions given below:

```
sbt: io.ebean:ebean:11.15.4:jar
sbt: io.ebean:ebean-agent:11.11.1:jar
sbt: io.ebean:ebean-annotation:3.11:jar
sbt: io.ebean:ebean-dbmigration:10.1.8:jar
sbt: io.ebean:ebean-migration:11.5.1:jar
sbt: io.ebean:persistence-api:2.2.1:jar
```

Please let me know if something is missing and more info is required. Thanks, Shubham.

**Comment by rbygrave** [comment] 2019-06-28 23:14
@shubhamp-zeotap  - Cool, the important bit was:
```
Caused by: java.lang.NullPointerException
	at io.ebeaninternal.server.deploy.DynamicPropertyAggregationFormula.load(DynamicPropertyAggregationFormula.java:43)
```

You do realise that I have pushed the fix and released 11.40.1 right?  You can update to 11.40.1 and confirm the fix.

Cheers, Rob.

**Comment by shubhamp-zeotap** [comment] 2019-06-29 22:32
Yes Rob, tested the fix. For this query on the model given above,

```
List<PartialSegment> segments = Ebean.find(PartialSegment.class)
        .select("segmentIdZat, min(status)")
        .fetchQuery("status", "*")
        .where().eq("segmentIdZat", 108L).findList();
```

This SQL was generated

```
[debug] io.ebean.SQL - txn[1008] select t0.segment_id_zat, min(t0.segment_status_id) from segments t0 where t0.segment_id_zat = ? group by t0.segment_id_zat; --bind(108)
[debug] io.ebean.SQL - txn[1008] select t0.status_id, t0.status, t0.country_ids from segment_status t0 where t0.status_id = ?  ; --bind(1, )
```

It is working fine in v11.40.1 as is but this aggregation feature is breaking when used together with Inheritance. Also found some unexpected behavior when using @Inheritance, @DiscriminatorColumn, and @DiscriminatorValue. Raising two more issues for these.


This blocker is removed. Thanks a lot! Shubham.

**Comment by shubhamp-zeotap** [comment] 2019-06-30 14:14
Hi Rob,

Unfortunately, I am observing one more issue here in the same part. Needed your inputs for that.

1) The secondary query for ```fetchQuery("status", "status")``` is not getting executed when I do setDisableLazyLoading(true). I am querying this way

```
        FetchGroup<PartialSegment> FG_SEGMENT = FetchGroup.of(PartialSegment.class)
                .select("segmentIdZat, min(status)")
                .fetchQuery("status", "status").build();

        List<PartialSegment> segments = Ebean.find(PartialSegment.class).setDisableLazyLoading(true)
                .select(FG_SEGMENT)
                .where().eq("segmentIdZat", 108L).findList();
```
This results in only one SQL query being executed (fetchQuery is not triggering the secondary query):
```
io.ebean.SQL - txn[1001] select t0.segment_id_zat, min(t0.segment_status_id) from segments t0 where t0.segment_id_zat = ? group by t0.segment_id_zat; --bind(108)
```

2) If I don't disable lazy loading and query like this:

```
        FetchGroup<PartialSegment> FG_SEGMENT = FetchGroup.of(PartialSegment.class)
                .select("segmentIdZat, min(status)")
                .fetchQuery("status", "status").build();

        List<PartialSegment> segments = Ebean.find(PartialSegment.class)
                .select(FG_SEGMENT)
                .where().eq("segmentIdZat", 108L).findList();
```

This cause fetchQuery to work fine and secondary SQL is executed
```
[debug] io.ebean.SQL - txn[1001] select t0.segment_id_zat, min(t0.segment_status_id) from segments t0 where t0.segment_id_zat = ? group by t0.segment_id_zat; --bind(108)
[debug] io.ebean.SQL - txn[1001] select t0.status_id, t0.status, t0.country_ids from segment_status t0 where t0.status_id = ?  ; --bind(1, )
```

But as soon as tried to access SegmentStatus of any PartialSegment entity, a third SQL gets triggered and loads the status bean fully, effectively rendering ```fetchQuery("status", "status")``` useless. 
```
[debug] io.ebean.SQL - txn[1001] select t0.status_id, t0.status, t0.country_ids from segment_status t0 where t0.status_id = ?  ; --bind(1, )
```

Is there any possible way I can load only specific properties on SegmentStatus using fetchQuery and without enabling lazy loading?

Thanks, Shubham.
