### ISSUE TITLE
update orm stackoverflow error 

### ISSUE THREAD

**Issue by benbenguo** [ebean-orm/ebean#1196] opened 2017-11-02 07:31 UTC
I build project with maven, and dependency version as show below

```xml
  <dependency>
            <groupId>org.avaje.ebean</groupId>
            <artifactId>ebean</artifactId>
            <version>9.5.1</version>
        </dependency>
```
I make orm like below code

``` java
public class User {
    @Id
    String id,

    @Basic
    @Column(name = "login_name", nullable = false, length = 50)
     String loginName

    @ManyToOne
    @JoinColumn(name = "crt_by", referencedColumnName = "id", nullable = false)
    User createdBy

    @ManyToOne
    @JoinColumn(name = "udp_by", referencedColumnName = "id", nullable = false)
    User lastupdatedBy
}
```

## Expected behavior
When I updated user and set lastupdatedBy with user object, I hoped it updated successfully.

## Actual behavior
But When I updated user and set lastupdatedBy with user object, I got an exception is "java.lang.StackOverflowError"

**Comment by rbygrave** [comment] 2017-11-06 10:06
Can you reproduce in the current version of Ebean?  It does not reproduce for me.

**Comment by rbygrave** [comment] 2017-11-13 08:36
Closing this in that I can't reproduce.  Reopen if/when you have a test case that reproduces the issue - thanks.

**Closed by rbygrave** 2017-11-13 08:36 UTC
