### ISSUE TITLE
Error loading property when using h2database JSON type

### ISSUE THREAD

**Issue by ooknight** [ebean-orm/ebean#2036] opened 2020-07-22 17:54 UTC
```sql
CREATE TABLE demo (
    id      BIGINT NOT NULL,
    config  JSON   NOT NULL
);
```

```java
@Entity
@Table(name="demo")
public class Demo {
    ...
    @DbJson
    @Column
    private DemoConfig config;
    ...
}
```

```java
public class DemoConfig {
    ...
    private String appid;
    private String appsecret;
    private String rule;
    ...
}
```

```java
@Test
public void test5() {
    DemoConfig config = new DemoConfig();
    config.setAppid("x");
    config.setAppsecret("y");
    config.setRule("z");
    Demo demo = new Demo();
    demo.setConfig(config);
    DB.insert(demo);
    List<Demo> result = DB.createQuery(Demo.class).findList();
    System.out.println(result);
}
```

```
javax.persistence.PersistenceException: Error loading on org.demo.entity.Demo.config

	at io.ebeaninternal.server.querydefn.DefaultOrmQuery.handleLoadError(DefaultOrmQuery.java:2080)
	at io.ebeaninternal.server.query.CQuery.handleLoadError(CQuery.java:812)
	at io.ebeaninternal.server.query.SqlBeanLoad.load(SqlBeanLoad.java:83)
	at io.ebeaninternal.server.deploy.BeanProperty.load(BeanProperty.java:631)
	at io.ebeaninternal.server.query.SqlTreeNodeBean$Load.loadProperties(SqlTreeNodeBean.java:337)
	at io.ebeaninternal.server.query.SqlTreeNodeBean$Load.initialise(SqlTreeNodeBean.java:458)
	at io.ebeaninternal.server.query.SqlTreeNodeBean.load(SqlTreeNodeBean.java:469)
	at io.ebeaninternal.server.query.CQuery.readNextBean(CQuery.java:457)
	at io.ebeaninternal.server.query.CQuery.hasNext(CQuery.java:535)
	at io.ebeaninternal.server.query.CQuery.readBean(CQuery.java:510)
	at io.ebeaninternal.server.query.CQueryEngine.find(CQueryEngine.java:438)
	at io.ebeaninternal.server.query.DefaultOrmQueryEngine.findId(DefaultOrmQueryEngine.java:171)
	at io.ebeaninternal.server.core.OrmQueryRequest.findId(OrmQueryRequest.java:421)
	at io.ebeaninternal.server.core.DefaultServer.findId(DefaultServer.java:1173)
	at io.ebeaninternal.server.core.DefaultServer.findOne(DefaultServer.java:1189)
	at io.ebeaninternal.server.querydefn.DefaultOrmQuery.findOne(DefaultOrmQuery.java:1572)
	at io.ebean.typequery.TQRootBean.findOne(TQRootBean.java:1572)
	at org.demo.DemoTest.test(DemoTest.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: io.ebean.text.TextException: Failed to parse JSON ["{\"appid\":null,\"appsecret\":null,\"rule\":null}"] as [simple type, class org.demo.entity.DemoConfig]
	at io.ebeaninternal.server.type.ScalarTypeJsonObjectMapper$Base.read(ScalarTypeJsonObjectMapper.java:212)
	at io.ebeaninternal.server.deploy.BeanProperty.read(BeanProperty.java:661)
	at io.ebeaninternal.server.query.SqlBeanLoad.load(SqlBeanLoad.java:72)
	... 40 more
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of org.demo.entity.DemoConfig (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('{"appid":null,"appsecret":null,"rule":null}')
 at [Source: (String)""{\"appid\":null,\"appsecret\":null,\"rule\":null}""; line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1451)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1081)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator._createFromStringFallbacks(ValueInstantiator.java:371)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromString(StdValueInstantiator.java:323)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromString(BeanDeserializerBase.java:1396)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:176)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:166)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4482)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3434)
	at io.ebeaninternal.server.type.ScalarTypeJsonObjectMapper$Base.read(ScalarTypeJsonObjectMapper.java:210)
	... 42 more
```

**Comment by rbygrave** [comment] 2020-07-23 23:55
We don't have a failing test.  Can you look to reproduce using TestDbJson_List and EBasicJsonList which has:

```java
  @DbJson(length = 500)
  PlainBean plainBean;

...

public class PlainBean {
  String name;
  long along;
  Timestamp timestamp;
  ...
}
```

**Comment by ooknight** [comment] 2020-07-26 18:17
[ebean-json-debug.zip](https://github.com/ebean-orm/ebean/files/4978104/ebean-json-debug.zip)
Above is my test code.
The h2 database field type generated by ebean unit test is varchar, and I use json.

![image](https://user-images.githubusercontent.com/5999599/88486269-267a5800-cfaf-11ea-8444-c4bb74f36800.png)

**Comment by rbygrave** [comment] 2020-08-04 10:01
So this is failing because the DB type is not the expected `VARCHAR` but instead `JSON`.

When this is read back as a String it is coming back as a escaped JSON string (all the quotes are escaped etc) - this is not valid JSON at this point and can not be parsed.

@ooknight If you want to add support for H2Database JSON type then you need to provide JDBC examples of how that type is both bound in PreparedStatement and read from ResultSet.  Noting that we don't desire change in the DML (so using `? FORMAT JSON` in dml isn't an acceptable option).

Over to you @ooknight

**Comment by rbygrave** [comment] 2020-08-05 04:55
At this stage we can close this issue.  We can revisit if / when someone wants to submit a PR for review to add support for H2Database JSON type (which does not seem useful).  Happy also for someone to add in example JDBC code showing the use of this type.

Closing for now.

**Closed by rbygrave** 2020-08-05 04:55 UTC
Labels: Waiting for more information
