### ISSUE TITLE
ebean 11.17 update to ebean 12.2， delete data error

### ISSUE THREAD

**Issue by xu1009** [ebean-orm/ebean#2084] opened 2020-10-19 06:45 UTC
when i update project ebean version from 11.17.5 to  ebean 12.2.3， delete data not work

delete dao java code

        ebeanServer.find(Message.class)
                .where()
                .eq("queue_name", queueName)
                .eq("message_id", taskId)
                .delete();

message bean

@Entity
@Table(catalog = "automatic_flow", name = "queue_message")
@Data
public class Message {

    @Id
    @Column(name = "id", nullable = false)
    private Long id;

    @Column(name = "message_id", nullable = false)
    private String messageId;

    @Column(name = "created_time", nullable = false)
    private LocalDateTime createdTime;

    @Column(name = "deliver_on", nullable = false)
    private LocalDateTime deliverOn;

    @Column(name = "queue_name", nullable = false)
    private String queueName;

    @Column(name = "popped", nullable = false)
    private Boolean popped;

    @Column(name = "offset_time_seconds", nullable = false)
    private Integer offsetTimeSeconds;

    @Column(name = "payload")
    private String payload;

}

error message

Caused by: java.sql.SQLException: No database selected
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3878)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2478)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2625)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2551)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2009)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5094)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1994)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at io.ebeaninternal.server.query.CQueryUpdate.execute(CQueryUpdate.java:92)
	at io.ebeaninternal.server.query.CQueryEngine.executeUpdate(CQueryEngine.java:82)

**Comment by rbygrave** [comment] 2020-10-19 08:03
Create a reproducing test case as a PR against https://github.com/ebean-orm-examples/example-minimal

But note that the stack trace above might not be complete (is that the FULL stack trace? is there a caused by not in the above?) ...

**Comment by rbygrave** [comment] 2020-10-19 22:57
I believe the "No database selected" error means that the JDBC URL you are using is not correct / does not specify the database.  I don't think this error has anything to do with Ebean.

**Comment by rbygrave** [comment] 2020-11-09 08:58
I'll close this issue at this point.

**Closed by rbygrave** 2020-11-09 08:58 UTC
Labels: Waiting for more information
