### ISSUE TITLE
Support Geometric types of Postgres

### ISSUE THREAD

**Issue by antonini** [ebean-orm/ebean#239] opened 2015-01-31 17:58 UTC
It would be nice that ebean supports geometric datatypes from Postgres. Those are listed on the following URL:
http://www.postgresql.org/docs/9.4/static/datatype-geometric.html

These are functions to be used with the previous datatypes.
http://www.postgresql.org/docs/9.0/static/functions-geometry.html

**Comment by rbygrave** [comment] 2015-02-02 06:19
This is a duplicate of #198 

I'll close this one for now leaving the original 198 open.

**Comment by rbygrave** [comment] 2015-02-02 19:35
Ok, not considering this a duplicate as separate types from #198

**Comment by rbygrave** [comment] 2017-05-20 13:31
Also note the example for Postgis is at: https://github.com/ebean-orm-examples/example-postgis

**Comment by rbygrave** [comment] 2019-09-11 21:14
Closing.  I'm unlikely to progress this myself until I need it.

**Closed by rbygrave** 2019-09-11 21:14 UTC
Labels: Limitation, Sponsor Me, enhancement
