### ISSUE TITLE
ScalarTypeWrapper doesn't handle "nullValue" correctly

### ISSUE THREAD

**Issue by instcode** [ebean-orm/ebean#2199] opened 2021-03-16 12:21 UTC
I have a column using a custom type with a converter as:

```java
    @Convert(converter = CustomDateConverter.class)
    CustomDate somedate;
```  

```java
@Converter
public class CustomDateConverter implements ScalarTypeConverter<CustomDate, Date> {
    @Override
    public CustomDate getNullValue() {
        // Return null value or null object here will cause either reading or binding issue
        return CustomDate.nullDate; 
    }

    @Override
    public Date unwrapValue(CustomDate attribute) {
        return attribute != null ? attribute.toDate() : null;
    }

    @Override
    public CustomDate wrapValue(Date dbData) {
        return (dbData != null) ? CustomDate.fromDate(dbData) : CustomDate.nullDate;
    }
}
```

From my investigation, I can see that ebean can't wrap / unwrap value correctly due to the following code in `ScalaTypeWrapper`:

```java
  @Override
  public B read(DataReader reader) throws SQLException {
    S sv = scalarType.read(reader);
    if (sv == null) {
      return nullValue;
    }
    return converter.wrapValue(sv);
  }

  public Object toJdbcType(Object value) {
    Object sv = converter.unwrapValue((B) value);
    if (sv == null) {
      return nullValue;
    }
    return scalarType.toJdbcType(sv);
  }
```

- If the value from database is "null", the converter doesn't have chance to wrap it into a "none" at custom type
- If the value from the entity property is "none", it never gets chance to translate into "null" at JDBC type

The fix would be:
```java
  @Override
  public B read(DataReader reader) throws SQLException {
    S sv = scalarType.read(reader);
    return converter.wrapValue(sv);
  }

  public Object toJdbcType(Object value) {
    Object sv = converter.unwrapValue((B) value);
    return scalarType.toJdbcType(sv);
  }
```
... which leaves the handling of null value / null object to the converter instead.

**Comment by rbygrave** [comment] 2021-03-16 22:21
I don't quite follow this yet.

Conceptually with ScalarTypeConverter the `unwrapValue()` and `wrapValue()` methods never get passed a value of null.  That is, a ScalarTypeConverter is not expected to or need to deal with null in those 2 methods. [I see the Oid test example does but that is a mistake/error in that example].

> If the value from database is "null", the converter doesn't have chance to wrap it into a "none" at custom type

Sure but the value returned is still the `nullValue` which would in this case be `CustomDate.nullDate` right?  



Sorry, can you have another go at explaining the issue? Have you seen an exception or some other background information?

**Comment by instcode** [comment] 2021-03-17 01:07
The `nullValue` here can't serve both purposes: the custom value of a entity's column, and the underlying jdbc value.

In this situation, because `nullValue` contains a null object of type `CustomDate`, when it's bound via `toJdbcType`, the value get passed to jdbc `scalarType` and it causes ClassCastException.

**Comment by rbygrave** [comment] 2021-03-17 04:32
Can you include the stack trace for the ClassCastException please?  That will help.  
Thanks, Rob.

**Comment by instcode** [comment] 2021-03-17 05:13
When binding a "CustomDate.nullValue" to a param, the exception was:
```
javax.persistence.PersistenceException: Error with property[7] dt[93]data[][com.example.common.types.CustomDate]
	at io.ebeaninternal.server.persist.Binder.bindSimpleData(Binder.java:377)
	at io.ebeaninternal.server.persist.Binder.bindObject(Binder.java:269)
	at io.ebeaninternal.server.persist.Binder.bindObject(Binder.java:221)
	at io.ebeaninternal.server.persist.Binder.bind(Binder.java:165)
	at io.ebeaninternal.server.persist.Binder.bind(Binder.java:127)
	at io.ebeaninternal.server.persist.Binder.bind(Binder.java:119)
	at io.ebeaninternal.server.persist.Binder.bind(Binder.java:111)
	at io.ebeaninternal.server.persist.ExeCallableSql.bindStmt(ExeCallableSql.java:91)
	at io.ebeaninternal.server.persist.ExeCallableSql.execute(ExeCallableSql.java:36)
	at io.ebeaninternal.server.persist.DefaultPersistExecute.executeSqlCallable(DefaultPersistExecute.java:99)
	at io.ebeaninternal.server.core.PersistRequestCallableSql.executeNow(PersistRequestCallableSql.java:53)
	at io.ebeaninternal.server.core.PersistRequest.executeStatement(PersistRequest.java:138)
	at io.ebeaninternal.server.core.PersistRequest.executeStatement(PersistRequest.java:122)
	at io.ebeaninternal.server.core.PersistRequestCallableSql.executeOrQueue(PersistRequestCallableSql.java:48)
	at io.ebeaninternal.server.persist.DefaultPersister.executeOrQueue(DefaultPersister.java:114)
	at io.ebeaninternal.server.persist.DefaultPersister.executeCallable(DefaultPersister.java:90)
	at io.ebeaninternal.server.core.DefaultServer.execute(DefaultServer.java:1931)
	at io.ebeaninternal.server.core.DefaultServer.execute(DefaultServer.java:1939)
Caused by: java.lang.ClassCastException: class com.example.common.types.CustomDate cannot be cast to class java.sql.Timestamp (com.example.common.types.CustomDate is in unnamed module of loader 'app'; java.sql.Timestamp is in module java.sql of loader 'platform')
at io.ebeaninternal.server.persist.Binder.bindSimpleData(Binder.java:333)
... 99 more
```

**Comment by rbygrave** [comment] 2021-03-17 08:10
Sorry, I think you trimmed the stack trace.  Can you include the full stack trace?  I want to see the root cause part of the stack.

**Comment by rbygrave** [comment] 2021-03-17 08:16
Can you also show me the code that would produce the stack trace?  I am thinking that code would be setting/using/binding a property with `CustomDate.nullValue`?  Can you show me the example that produces the error? [and the full stack trace ideally].

Thanks, Rob.

**Comment by instcode** [comment] 2021-03-17 08:38
Sorry, I cut off is only our application code to not disclose it, also the package "com.example" was made up as well. The code is just using `CallableSql` to call a stored procedure using parameter binding. Let me try to produce a sample code for reproduce that.

**Comment by rbygrave** [comment] 2021-03-17 09:06
Yeah cool. I probably only need to see approximately how to reproduce it.  I'm guessing CallableSql with a bind parameter value of `CustomDate.nullValue`.

**Comment by instcode** [comment] 2021-03-17 09:30
A fragment of test:
```java
@Entity
@Table(name = "TableX")
@Getter
@Setter
public class MyEntity {
    @Id
    @NonNull
    String id;

    @Convert(converter = CustomDateConverter.class)
    CustomDate somedate;
}
```

```java
        MyEntity entity = new MyEntity();
        entity.setId("123");
        entity.setCustomDate(CustomDate.nullDate);
        DB.getDefault().save(entity); // Save successfully
        MyEntity result = DB.getDefault().createQuery(MyEntity.class).where().eq("somedate", CustomDate.nullDate).findOne(); // Class Cast Exception
        Assertions.assertNotNull(result);
```

The exception is:
```
javax.persistence.PersistenceException: Error with property[0] dt[93]data[][****]

	at io.ebeaninternal.server.persist.Binder.bindSimpleData(Binder.java:377)
	at io.ebeaninternal.server.persist.Binder.bindObject(Binder.java:269)
	at io.ebeaninternal.server.persist.Binder.bindObject(Binder.java:221)
	at io.ebeaninternal.server.expression.DefaultExpressionRequest.bind(DefaultExpressionRequest.java:71)
	at io.ebeaninternal.server.query.CQueryPredicates.bind(CQueryPredicates.java:168)
	at io.ebeaninternal.server.query.CQuery.prepareResultSet(CQuery.java:365)
	at io.ebeaninternal.server.query.CQuery.prepareBindExecuteQueryWithOption(CQuery.java:325)
	at io.ebeaninternal.server.query.CQuery.prepareBindExecuteQuery(CQuery.java:321)
	at io.ebeaninternal.server.query.CQueryEngine.findMany(CQueryEngine.java:371)
	at io.ebeaninternal.server.query.DefaultOrmQueryEngine.findMany(DefaultOrmQueryEngine.java:131)
	at io.ebeaninternal.server.core.OrmQueryRequest.findList(OrmQueryRequest.java:452)
	at io.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1495)
	at io.ebeaninternal.server.core.DefaultServer.findOne(DefaultServer.java:1169)
	at io.ebeaninternal.server.querydefn.DefaultOrmQuery.findOne(DefaultOrmQuery.java:1607)
	at io.ebeaninternal.server.expression.DefaultExpressionList.findOne(DefaultExpressionList.java:471)
	at xxxxxx.EntityOperationSupportTest.testMe(EntityOperationSupportTest.java:38)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
Caused by: java.lang.ClassCastException: class *.CustomDate cannot be cast to class java.sql.Timestamp (*.CustomDate is in unnamed module of loader 'app'; java.sql.Timestamp is in module java.sql of loader 'platform')
	at io.ebeaninternal.server.persist.Binder.bindSimpleData(Binder.java:333)
	... 80 more

```

**Comment by instcode** [comment] 2021-03-17 09:31
It doesn't have to be a CallableSql. It's reproducible as long as the code runs over the `Binder.bindObject` on `ScalarTypeWrapper`.

**Comment by rbygrave** [comment] 2021-03-17 10:26
Yes, I think the fix is literally just to remove the `if (sv == null) { return nullValue; } ` ... as you suggest.

```java
  public Object toJdbcType(Object value) {
    Object sv = converter.unwrapValue((B) value);
    // if (sv == null) {    
    //   return nullValue;  // <-- It returns the "nullValue" which is "CustomDate.nullValue" here but we want "null" instead
    // }
    return scalarType.toJdbcType(sv);
  }
```

**Comment by instcode** [comment] 2021-03-17 11:04
Yes, it would fix the parameter binding in case we use `ScalarTypeConverter`. However, if someone uses standard JPA `AttributeConverter` which doesn't have the `getNullValue` method, he/she can't convert `null` to a custom null object because the code in `ScalarTypeWrapper` doesn't process that way:
```java
@Override
  public B read(DataReader reader) throws SQLException {
    S sv = scalarType.read(reader);
    if (sv == null) {
      return nullValue;
    }
    return converter.wrapValue(sv);
  }
```
That's why I think we may want to fix this (and other similar methods) as well if you think that JPA `AttributeConverter` is the future (I read some document that you mention about this). Just this may break some user systems :)

**Comment by rbygrave** [comment] 2021-03-17 20:58
> uses standard JPA AttributeConverter which doesn't have the getNullValue method, he/she can't convert null to a custom null object 

Yes, I can see that now.

I am pondering if this part of the issue is more a design issue in terms of this subtle difference between ScalarTypeConverter  and AttributeConverter.

For Ebean ScalarTypeConverter the javadoc says:

```java
 * Matches the functionality of javax.persistence.AttributeConverter
 * <p>
 * In general AttributeConverter should be used in preference to this
 * ScalarTypeConverter as it is JPA standard and offers the same functionality.
 * </p>
 * <p>
 * For Ebean we will look to deprecate this interface in preference to AttributeConverter.
 * </p>
```

Ultimately there is a subtle design mismatch between these 2 API's with Ebean ScalarTypeConverter having the additional `getNullValue()` method (which is not present on JPA AttributeConverter).

I'm pondering if the correct thing to do is actually remove the `ScalarTypeConverter.getNullValue()` method with the thought to make these interfaces _exactly compatible wrt null treatment_.  In theory this would make it clear that "null conversion logic" needs to be in the wrapValue() and unwrapValue() methods [rather than outside in ScalarTypeWrapper].


**Status:**
1)  I'll push the commit for the "fix the parameter binding in case we use ScalarTypeConverter"
2)  We have an issue for AttributeConverter with a custom null value
3)  Longer term we have design issue in terms of subtle difference between ScalarTypeConverter and AttributeConverter and maybe should look to actually deprecate ScalarTypeConverter (once we sort 2).

**Next steps:**
Failing test case for AttributeConverter with a custom null value.

**Comment by rbygrave** [comment] 2021-03-17 21:26
Note for people reading this issue.  When the null value is actually `null` then there isn't an issue. This issue occurs when we want to use a special value (on the bean side) to represent null.

**Comment by rbygrave** [comment] 2021-03-18 03:21
Pushed a fix for - "standard JPA AttributeConverter which doesn't have the getNullValue method, he/she can't convert null to a custom null object"

The fix is for AttributeConverterAdapter to probe the AttributeConverter for the nullValue rather than just assuming it is null.  I'm happy with this approach and keeps it in line with what we have.  We still need to ponder if ScalarTypeConverter should be deprecated at some point but no rush on this.

**Closed** 2021-03-18 03:24 UTC
Labels: bug
