### ISSUE TITLE
Lazy Loading does not occur after executing a select distinct query

### ISSUE THREAD

**Issue by jnehlmeier** [ebean-orm/ebean#2033] opened 2020-07-07 15:17 UTC
## Expected behavior

Lazy loading of `@ManyToOne(fetch = FetchType.LAZY)` property should occur when getter is called.

## Actual behavior

When calling the getter `null` is returned. In the example below this happens for `Definition.getRuleSet()`.

### Steps to reproduce

Models:
```java
@Entity
public class Specification extends Model {

  @Id
  private Long id;

  @Basic(optional = false)
  private final int version;

  @Basic(optional = false)
  private final int release;

  public Specification(int version, int release) {
    this.version = version;
    this.release = release;
  }

  public Long getId() { return id; }
  public int getVersion() { return version; }
  public int getRelease() { return release; }

  @Override
  public String toString() {
    return "[id: " + getId() + ", name: " + getVersion() + "." + getRelease() + "]";
  }
}

@Entity
public class RuleSet extends Model {

  @Id
  private Long id;

  @Basic(optional = false)
  private final String name;

  public RuleSet(String name) {
    this.name = name;
  }

  public Long getId() { return id; }
  public String getName() { return name; }

  @Override
  public String toString() {
    return "[id: " + getId() + ", name: " + getName() + "]";
  }
}

@Entity
public class Definition extends Model {

  @Id
  private Long id;

  @Basic(optional = false)
  private final String name;

  @ManyToOne(optional = false)
  private final Specification specification;

  @ManyToOne(fetch = FetchType.LAZY, optional = false)
  private final RuleSet ruleSet;

  public Definition(String name, Specification specification, RuleSet ruleSet) {
    this.name = name;
    this.specification = specification;
    this.ruleSet = ruleSet;
  }

  public Long getId() { return id; }
  public String getName() { return name; }
  public RuleSet getRuleSet() { return ruleSet; }
  public Specification getSpecification() { return specification; }

  @Override
  public String toString() {
    return "[id: " + getId() + ", name: " + getName() +
        ", specification: " + getSpecification() +
        ", ruleSet: " + getRuleSet() + "]";
  }
}
```
Note that `Definition.specification` has `FetchType.EAGER` as default while `Definition.ruleSet` has `FetchType.LAZY`. Also note that the `toString()` methods are used to trigger lazy loading.

Test Code:
```java
try (var tx = db.beginTransaction()) {
  var spec11 = new Specification(1,1);
  spec11.save();
  var spec12 = new Specification(1,2);
  spec12.save();
  var ruleSet = new RuleSet("Rules");
  ruleSet.save();

  new Definition("Definition 1", spec11, ruleSet).save();
  new Definition("Definition 2", spec11, ruleSet).save();

  new Definition("Definition 1", spec12, ruleSet).save();
  new Definition("Definition 2", spec12, ruleSet).save();

  tx.commit();
}

var defs = new QDefinition()
  .setDistinct(true)
  .where()
    .specification.version.eq(1)
    .specification.release.eq(1)
  .findList();

defs.forEach(System.out::println);
```

Output **with** setDistinct(true)
```
txn[1002] select distinct t0.name, t0.specification_id from definition t0 join specification t1 on t1.id = t0.specification_id  where t1.version = ? and t1.release = ?; --bind(1,1)
txn[1002] FindMany type[Definition] origin[MD8OR.A.A] exeMicros[8553] rows[2] predicates[t1.version = ? and t1.release = ?] bind[1,1]
txn[1003] select t0.id, t0.version, t0.release from specification t0 where t0.id = ?  ; --bind(1, )
txn[1003] FindMany mode[+lazy] type[Specification] origin[MD8OR.A.A] lazyLoadProp[version] load[path:specification batch:1] exeMicros[2922] rows[1] predicates[] bind[1, ]

[id: null, name: Definition 2, specification: [id: 1, name: 1.1], ruleSet: null]
[id: null, name: Definition 1, specification: [id: 1, name: 1.1], ruleSet: null]
```
As can be seen, Ebean selects the `specification_id` (which is marked as `EAGER`) but not the `rule_set_id` (which is marked as `LAZY`). When lazy loading is triggered through `toString()` only the `Specification` is loaded but not the `RuleSet`.

Output **without** setDistinct(true)
```
txn[1002] select t0.id, t0.name, t0.specification_id from definition t0 join specification t1 on t1.id = t0.specification_id  where t1.version = ? and t1.release = ?; --bind(1,1)
txn[1002] FindMany type[Definition] origin[MD8OR.A.A] exeMicros[5459] rows[2] predicates[t1.version = ? and t1.release = ?] bind[1,1]
txn[1003] select t0.id, t0.name, t0.specification_id, t0.rule_set_id from definition t0 where t0.id = any(?); --bind(Array[2]={2,1})
txn[1003] FindMany mode[+lazy] type[Definition] origin[MD8OR.A.A] lazyLoadProp[ruleSet] load[path:null batch:2] exeMicros[9622] rows[2] predicates[t0.id = any(?)] bind[Array[2]={2,1}]
txn[1004] select t0.id, t0.version, t0.release from specification t0 where t0.id = ?  ; --bind(1, )
txn[1004] FindMany mode[+lazy] type[Specification] origin[MD8OR.A.A] lazyLoadProp[version] load[path:specification batch:1] exeMicros[2563] rows[1] predicates[] bind[1, ]
txn[1005] select t0.id, t0.name from rule_set t0 where t0.id = ?  ; --bind(1, )
txn[1005] FindMany mode[+lazy] type[RuleSet] origin[MD8OR.A.A] lazyLoadProp[name] load[path:ruleSet batch:1] exeMicros[2507] rows[1] predicates[] bind[1, ]

[id: 2, name: Definition 2, specification: [id: 1, name: 1.1], ruleSet: [id: 1, name: Rules]]
[id: 1, name: Definition 1, specification: [id: 1, name: 1.1], ruleSet: [id: 1, name: Rules]]
```
Here we can see that Ebean also only selects the `specification_id` but not the `rule_set_id` (`EAGER` vs `LAZY` behavior). As soon as lazy loading for `LAZY` field `ruleSet` is triggered, Ebean selects the full `Definition` rows again for all known `Definition` ids to get knowledge about the `RuleSet` foreign key ids so it can load `RuleSet`s lazily.

---

Debugging revealed that the `EntityBeanIntercept` instances attached to the loaded `Definition` entities are in state `NEW`. I would assume this happens because the loaded entities do not have the `id` property set (since it wasn't selected because of the distinct query) and Ebean now assumes these are newly created entities that can not lazy load. However for fields marked as `EAGER` (specification) Ebean still does the lazy query somehow once calling the `Definition.getSpecification()` method.

See code in `EntityBeanIntercept.preGetter`: https://github.com/ebean-orm/ebean/blob/361de9ea998872ad80a1d2e9edaa49f9473b02e1/src/main/java/io/ebean/bean/EntityBeanIntercept.java#L907-L911

Removing `setDistinct(true)` fixes the lazy loading issue. Alternatively one can mark the field as `EAGER`.

**Comment by jnehlmeier** [comment] 2020-07-08 14:11
I have updated the issue with a more complete example.

**Comment by rbygrave** [comment] 2020-07-09 04:10
> When lazy loading is triggered through toString() 

Important note that `toString()` on an entity bean along with `equals()` and `hashCode()` methods are intentionally **_not_** modified for interception and are not expected to invoke lazy loading.  The reason the `toString()` method above invokes lazy loading is because it is calling the getter methods.

**Comment by rbygrave** [comment] 2020-07-09 04:33
I don't think this is a bug. I think this is correct behaviour.

```java
new QDefinition()
  .setDistinct(true)
```
The important point here is this is a `.setDistinct(true)` query where the select clause has NOT been explicitly set (meaning that the properties/columns selecting are driven off the annotations - FetchType.LAZY etc and hence the fk for ruleSet isn't in the select clause).

```sql
select distinct t0.name, t0.specification_id from definition t0 ...  -- t0.rule_set_id is not here as expected
```
Hence the `t0.specification_id` is in the select clause BUT NOT t0.rule_set_id - the fk column for ruleSet .

I believe what you are looking for in this case is:
```java
QDefinition d = QDefinition.alias()
new QDefinition()
  .setDistinct(true).select(d.name, d.specification, d.ruleSet)  // explicitly define select properties when using distinct
  ...
```
So try using the explicit select clause like above and I believe you will see what you expect.  Note that we are actually changing the distinct logic here (as now the distinct also includes t0.rule_set_id - so this could be significant / can have an impact). 

That is, the lazy loading on ruleSet doesn't happen because ruleSet (ManyToOne) was not in the original select clause and hence comes out as null in the toString output - this is all correct and expected.

In general the thinking is that once we use setDistinct(true) we are generally wanting to perform "distinct" on very known usually explicitly defined select clause.  That is, setDistinct(true) most often means we also explicitly specify the select() properties explicitly.

Does that make sense?

**Comment by jnehlmeier** [comment] 2020-07-09 14:12
> Important note that toString() on an entity bean along with equals() and hashCode() methods are intentionally not modified for interception and are not expected to invoke lazy loading. The reason the toString() method above invokes lazy loading is because it is calling the getter methods.

Yes in the example code I used `toString` for simplicity. In our real code we called the getter in application code and actually got a `NullPointerExeption` because we expected lazy loading to work.

> So try using the explicit select clause like above and I believe you will see what you expect. Note that we are actually changing the distinct logic here (as now the distinct also includes t0.rule_set_id - so this could be significant / can have an impact).

It does work for the given example above, but I can also make an example where this does not work. Namely when we have a `OneToMany` relation and the foreign key is in the other table. Because Ebean does not select the `id` column for distinct queries, it is impossible to write a follow up lazy loading query in the form of `where foreign_key_id in (<primary keys>)`. See below the `Shop` example.

> Does that make sense?

Only to a certain extend. I can agree that it is better to specify columns when using distinct so it is visible to the developer on what columns distinction will be calculated, however I also think that in the absence of a select definition the default behavior must work correctly without surprises. With distinct and no select definition, Ebean must select all columns of the Entity, otherwise you are in trouble. See `Shop` example below.

> That is, the lazy loading on ruleSet doesn't happen because ruleSet (ManyToOne) was not in the original select clause and hence comes out as null in the toString output - this is all correct and expected.

I don't agree here. If you take a closer look at the initial query you see it selects basically the same columns whether or not I use `setDistinct(true)` or `setDistinct(false)`. The only difference is that the distinct query does not select the `id` column. In both queries the `rule_set_id` column is not selected, however in one case lazy loading works but in the other case it doesn't. So whether or not lazy loading works does not depend on the fact whether or not the `rule_set_id` column is selected in the initial query. It seems to depend on the fact whether or not the `id` column is selected.
I think as long as you don't use a DTO query lazy loading must always happen and indeed it does as long as you don't use `setDistinct(true)`. Otherwise the whole concept of lazy loading and partial objects would be broken and migrating away from JPA would result in some surprises.


I thought about the default behavior of a distinct query when no select is explicitly given to Ebean and the fact that the `id` column is not selected for such queries. Personally I would say that the current behavior of not selecting the `id` column and selecting other columns the ordinary way (`LAZY` not included, `EAGER` included) is wrong.

Consider the following example:
```java
Shop (id, name, city_id)
Product (id, price, discount, shop_id)
City (id, name)
```
The `Shop` Entity has  `@ManyToOne(fetch = LAZY) city` and `@OneToMany(fetch = LAZY) products` fields. Now also consider the database has two shops stored and these two shops accidentally having the same name but are located in different cities, so they are really different shops.

If we now make a distinct query asking for all shops, we would only get a single result instead of two: 
```java
new QShop().setDistinct(true).findList();

txn[1002] select distinct t0.name from shop t0; --bind()
txn[1002] FindMany type[Shop] origin[B1Sy4w.A.A] exeMicros[3881] rows[1] predicates[] bind[]

[id: null, name: Pizza shop, city: null, products: null]
```
Because Ebean omits columns and only selects the name column, the result is unexpected since we have two distinct shops in the database, not just a single one. IMHO this is a plain wrong result that nobody would expect (I asked some co workers). In addition lazy loading did not work as already discovered.

Now lets change the query according to your suggestion above
```
var s = QShop.alias();
new QShop().setDistinct(true).select(s.id, s.name, s.city, s.products).findList();

txn[1003] select distinct t0.name, t0.city_id from shop t0; --bind()
txn[1003] FindMany type[Shop] origin[B1Sy4w.A.A] exeMicros[5153] rows[2] predicates[] bind[]
txn[1004] select t0.id, t0.name from city t0 where t0.id = any(?); --bind(Array[2]={1,2})
txn[1004] FindMany mode[+lazy] type[City] origin[B1Sy4w.A.A] lazyLoadProp[name] load[path:city batch:2] exeMicros[13073] rows[2] predicates[t0.id = any(?)] bind[Array[2]={1,2}]

[id: null, name: Pizza shop, city: [id: 1, name: City 1], products: null]
[id: null, name: Pizza shop, city: [id: 2, name: City 2], products: null]
```
Now `city_id` is selected as well and thus lazy loading works. `id` is still ignored by Ebean even though it is specified. Now the query returns the expected two results since `city_id` is included. However since the `shop_id` is stored in the `products` table AND Ebean does not load the `shop.id` column, there is no way to make a follow up query to lazy load products and indeed products is null. So in this case lazy loading products does not work at all, unless we remove distinct.  

In short I believe the current behavior is broken. Omitting the `id` column for distinct queries is wrong because it can make lazy loading impossible as seen above. Omitting columns based on the `fetchType` setting on fields for distinct queries is wrong because it can result in working queries which do not return the expected result as seen above.

I think as soon as `setDistinct(true)` is used without a concrete definition of columns/fields to select, Ebean MUST SELECT ALL columns of that entity to make sure that distinct works as expected. Not providing a `select(...)` call basically means `SELECT *`. In the `setDistinct(false)` case Ebean can do some nice optimizations and omit columns since it does not have an effect on the rows selected but Ebean can not do that when `setDistinct(true)` is used.

Does that makes sense?

**Comment by rbygrave** [comment] 2020-07-09 22:21
A question then, given the 2 SQL queries:
```sql
select t0.id, t0.name, t0.city_id from shop t0
```
```sql
select distinct t0.id, t0.name, t0.city_id from shop t0
```
What is the motivation for using `distinct` here?  (Given that the id column being the primary key is by definition a distinct value)

In the code above:
```java
new QShop().setDistinct(true).select(s.id, s.name, s.city, s.products).findList();
```
What is the motivation for using `.setDistinct(true)` when the select clause includes `s.id` ?

**Comment by jnehlmeier** [comment] 2020-07-10 08:39
> In the code above:
> 
> ```java
> new QShop().setDistinct(true).select(s.id, s.name, s.city, s.products).findList();
> ```
> 
> What is the motivation for using `.setDistinct(true)` when the select clause includes `s.id` ?

Hehe, understandable question. Actually the queries for the Shop example did originally contain a `where` clause but I removed it because it was irrelevant to produce the issues. However you are right, the query without the `where` looks a bit silly. But I think we can agree that one can expect that
```java
new QShop().findList();
new QShop().select(s.id, s.name, s.city).findList();
new QShop().setDistinct(true).findList();
new QShop().setDistinct(true).select(s.id, s.name, s.city).findList();
```
should all behave exactly the same without any surprises (just like in SQL) including lazy loading. Even though the distinct queries might look silly, the library is expected to handle it correctly. Currently they can produce different results in terms of row count and have different lazy loading behavior.

Anyways, a more reasonable query for the Shop example might be:
```java
// Find all shops with cheap products or with good deals (= high discount)
new QShop()
  .setDistinct(true)
  // fixes city lazy load and distinct for same named shops in 
  // different cities. Does not fix products lazy load.
  //.select(s.id, s.name, s.city, s.products) 
  .or()
    .products.price.lt(50)
    .products.discount.gt(40)
  .endOr()
  .findList();
```
Since `products` is a one-to-many relation and the `or` condition could match twice for the same product (once for price, once for discount) a shop might be duplicated, so we need the distinct. Since products of two shops might match, it is important that all columns of `shop` are selected, otherwise the distinct might reduce erroneously the number or matched shops as described in my answer before.

**Comment by rbygrave** [comment] 2020-07-10 09:12
> a shop might be duplicated, so we need the distinct

Yes BUT Ebean should add that for us automatically.  So remove setDistinct(true) ... and run that query and paste the SQL here.

**Comment by jnehlmeier** [comment] 2020-07-10 11:34
```java
new QShop()
  .or()
    .products.price.lt(50)
    .products.discount.gt(40)
  .endOr()
  .findList();


txn[1002] select distinct on (t0.id) t0.id, t0.name from shop t0 left join product u1 on u1.shop_id = t0.id  where (u1.price < ? or u1.discount > ?); --bind(50,40)
txn[1002] FindMany type[Shop] origin[B1Sy4w.A.A] exeMicros[9293] rows[2] predicates[(u1.price < ? or u1.discount > ?)] bind[50,40]
txn[1003] select t0.id, t0.name, t0.city_id from shop t0 where t0.id = any(?); --bind(Array[2]={1,2})
txn[1003] FindMany mode[+lazy] type[Shop] origin[B1Sy4w.A.A] lazyLoadProp[city] load[path:null batch:2] exeMicros[8121] rows[2] predicates[t0.id = any(?)] bind[Array[2]={1,2}]
txn[1004] select t0.id, t0.name from city t0 where t0.id = any(?); --bind(Array[2]={1,2})
txn[1004] FindMany mode[+lazy] type[City] origin[B1Sy4w.A.A] lazyLoadProp[name] load[path:city batch:2] exeMicros[3915] rows[2] predicates[t0.id = any(?)] bind[Array[2]={1,2}]

[id: 1, name: Pizza shop, city: [id: 1, name: City 1], products: BeanList deferred ]
[id: 2, name: Pizza shop, city: [id: 2, name: City 2], products: BeanList deferred ]
```

Wow ok, this works. But honestly, how should I have known that? When migrating from JPA you would add the `setDistinct(true)` naturally since comparable JPQL queries require DISTINCT and in SQL it is also required. The JavaDoc says "Set whether this query uses DISTINCT.". So there is literally no indicator that using it with EBean manually will have all sorts of undesired consequences. 
Also any developer not familiar with EBean might raise the issue that distinct is missing when doing code reviews. IMHO it is too hidden and it should be allowed to make it explicit to make it look correct in code.

But of course I can also understand the thinking behind it. If I just have a single shop with 3 products and making a where on products then I should only get that single shop. So using an ORM level of view it makes sense. However given that EBean is so close to SQL and using Query Beans feels like writing SQL, it is super unintuitive when thinking on SQL level.

I guess the JavaDoc of `setDistinct()` needs some great improvements then, indicating when to use it, when not to use it and which consequences it's use has (id is null, *ToMany lazy load will not work at all, *ToOne lazy load will only work when explicitly selecting the foreign key columns in case they are marked `LAZY`).

**Comment by rbygrave** [comment] 2020-07-12 21:01
> Wow ok, this works.

Yes.


>  But honestly, how should I have known that? When migrating from JPA you would add the setDistinct(true) naturally since comparable JPQL queries require DISTINCT

I hear your pain. JPQL has conditioned developers to it's design somewhat.

I have been saying for many years that JPQL isn't very good. When we programmatically add a predicate and that predicate _happens_ to be on a "ToMany path" with JPQL we now also need to explicitly add distinct to the JPQL query.  If we don't we get a non-useful result.  Any query building code now needs to be that much smarter with JPQL for no good reason (because the result without the sql distinct isn't useful).


> EBean is so close to SQL and using Query Beans feels like writing SQL

This is true to a point and then it becomes non-true (queries involving "ToMany paths") remembering that a single ORM query can "build graphs to any depth" (vs "relatively flat relations").


Happy to take PR's to improve the documentation and javadoc etc.

**Comment by jnehlmeier** [comment] 2020-07-13 08:57
> Happy to take PR's to improve the documentation and javadoc etc.

Given amount of consequences I am wondering if there is an even better solution. I mean we are selecting entities but
1. they have no ID
2. Lazy loading is inconsistent (works for *ToOne if column has been selected, never works for *ToMany)

I think it would be better to protect developers from such behavior so the library has less surprises. But I am struggling to find a good solution. I am thinking about something like

1. `selectDistinct(Column, Column...)` which throws exception when providing the `@Id` column(s). But it does not make clear that lazy loading might not work.
2. `findDtoDistinct()` so it is clear that lazy loading will not work at all. Must also throw exception when `@Id` should be mapped into the DTO.

Reason is that I strongly believe that Entities loaded from DB should always have an ID and always have working lazy loading. Otherwise it is not an ORM managed Entity and you are kind of in the same situation as you described with JPQL / DISTINCT: Code paths now need to account for that in case such a "half working" Entity is passed in. Only newly created entities should have no ID and no lazy loading.

And as a side note: That `EntityBeanIntercept` is in state `NEW` when the entity is loaded using `setDistinct(true)` could also easily be overlooked and might cause subtle bugs.

**Comment by rbygrave** [comment] 2020-07-13 20:27
## Summary

- There was confusion due to the use of `setDistinct(true)` when it should not have been used.  Noting that Ebean automatically deals with ToMany paths in predicates and fetching and automatically adding a sql distinct as needed.  This is unlike JPQL where developers need to remember to explicitly add distinct with predicates on ToMany paths.
- Ebean is worked as designed and expected and there is not anything to add or change here

@jnehlmeier  Looking at the last comments we need a reset. If there is still confusion then we must start fresh again with the ORM query, generated SQL and description of what is confusing or unexpected about that. 

As I see it you need to simply remove the use of `setDistinct(true)` [and Ebean will add the sql distinct as is the correct and proper thing to do].   Your comments suggest your app does not yet need Ebean's `setDistinct(true)` at all but note that it is there for a reason etc.

Also remembering that Ebean's query language design is mature at 14 years old.  This hasn't changed in 14 years and I'm not expecting it to.

I'll close this ticket.  You can reopen it but do so with a fresh clean start including the orm query, sql and explanation.

Thanks, Rob.

**Closed by rbygrave** 2020-07-13 20:27 UTC
