### ISSUE TITLE
A bug about of ScalarType of Enum when query

### ISSUE THREAD

**Issue by liudaomanbu** [ebean-orm/ebean#1250] opened 2018-02-05 06:34 UTC
**When an enum type has an abstract method, the ebean will have throw PersistenceException of "No ScalarType registered for class ncommon.enums.ReportType$1".**

Through the debug,i found the reason.
Ebean use a ConcurrentHashMap<Class<?>, ScalarType<?>> typeMap to Keep the relationship between Class Object and ScalarType Object.
And use Object.getClass() result to get ScalarType Object from typeMap in com.avaje.ebeaninternal.server.persist.Binder.bindObject(DataBind dataBind, Object value) method.

But when enum type have abstract methods,the result of  Object.getClass() is a anonymous Class of super enum Class.
Then,the Exception happened.
![qq 20180205140751](https://user-images.githubusercontent.com/21155988/35790911-b4fb0da6-0a7f-11e8-9c73-af498eaae3f4.png)

![qq 20180205141209](https://user-images.githubusercontent.com/21155988/35790900-aafb694a-0a7f-11e8-9ce0-806e87372cc3.png)

**I think that fix the bug is very simple.
We can register all anonymous Class of super enum Class to typeMap ,or we can use the super class to key when the result of  Object.getClass() is a anonymous Class of super enum Class.**

**But after I compare the code, I find that the latest version still doesn't fix the bug.**

PS:**All Entity Class use a common typeMap,But the annotation of Enumerated can be set different values to a common Enum Class in different Entity Class.**
I think it's a bad design.

**Comment by liudaomanbu** [comment] 2018-02-05 08:44
```
try {
      EbeanServer server=Ebean.getDefaultServer();
      Field relationalQueryEngineField=server.getClass().getDeclaredField("relationalQueryEngine");
      relationalQueryEngineField.setAccessible(true);
      DefaultRelationalQueryEngine engine= (DefaultRelationalQueryEngine) relationalQueryEngineField.get(server);
      Field binderField=engine.getClass().getDeclaredField("binder");
      binderField.setAccessible(true);
      Binder binder= (Binder) binderField.get(engine);
      Field typeManagerField=binder.getClass().getDeclaredField("typeManager");
      typeManagerField.setAccessible(true);
      DefaultTypeManager typeManager= (DefaultTypeManager) typeManagerField.get(binder);
      ScalarType<ReportType> reportTypeScalarType=typeManager.getScalarType(ReportType.class);
      Field typeMapField=typeManager.getClass().getDeclaredField("typeMap");
      typeMapField.setAccessible(true);
      Map<Class<?>, ScalarType<?>> typeMap=(Map<Class<?>, ScalarType<?>>) typeMapField.get(typeManager);
      Arrays.stream(ReportType.values()).forEach(reportType->{
        typeMap.put(reportType.getClass(), reportTypeScalarType);
      });
    } catch (NoSuchFieldException | SecurityException | IllegalArgumentException | IllegalAccessException e) {
      e.printStackTrace();
      throw new RuntimeException(e);
    }
```
I use reflect to put the anonymous Class,then the Exception don't happened.

**Comment by rbygrave** [comment] 2018-02-05 23:35
Step 1 is to describe the problem fully or provide a failing test case.  We don't have that here yet so we need to do that first.

> an enum type has an abstract method, 

This is not sufficient as it doesn't explain what concrete types are defined and how they are used. This must be done to fully understand the issue as this includes DDL and constraints etc (it is not just about runtime).

So before anything else happens we need a good full description (or test case). We need ReportType, all the concrete subtypes of ReportType and where and how they are used.

**Comment by liudaomanbu** [comment] 2018-02-06 05:59
![qq 20180206130417](https://user-images.githubusercontent.com/21155988/35843446-2f84d3f4-0b43-11e8-830c-c1e1ca742d8b.png)
![qq 20180206130611](https://user-images.githubusercontent.com/21155988/35843503-82b95bc6-0b43-11e8-80e1-16ef19ca0889.png)
![qq 20180206130614](https://user-images.githubusercontent.com/21155988/35843566-e21d829a-0b43-11e8-8219-e106a7981781.png)
![qq 20180206134529](https://user-images.githubusercontent.com/21155988/35843647-41dd3b30-0b44-11e8-8d96-6e88521b6532.png)
![qq 20180206134656](https://user-images.githubusercontent.com/21155988/35843696-8973e156-0b44-11e8-8a79-f1599f6cbf4c.png)

That's all.
The reason is that the Class Object get by Enumerated annotation in Field always ReportType.class,But the ReportType Enum Objects must be anonymous Class when ReportType.class have abstract methods.
So value.getClass() can't get the ScalarType from TypeManager.

**Comment by liudaomanbu** [comment] 2018-02-06 06:22
And another question is this.
![qq 20180206141602](https://user-images.githubusercontent.com/21155988/35844426-64722c38-0b48-11e8-82a0-ee759cdba78a.png)

This is a perfectly possible and reasonable situation,an annotation can be set different value in different class.
But in fact, all classes share a map,It will be throw Exception in runtime.
I think it's a bad design.
Maybe you should let each class enjoy its own map?

**Comment by rbygrave** [comment] 2018-02-07 01:08
> When an enum type has an abstract method, the ebean will have throw PersistenceException of "No ScalarType registered for class ncommon.enums.ReportType$1".

The issue you describe does not reproduce against current Ebean.  You will need to create a test case that reproduces the issue you claim.

----
> And another question is this.

It is not recommended to "cross post" - put more than one question / issue into a single ticket is bad form.  In this case I'll answer this with ... `No, we don't allow people to map a single Enum multiple ways`.  The reason is that we then are unable to bind by type and can only bind by path and type ... which is too big a limitation on findNative and other binding that doesn't know about `property path`.

So no, you need to use a different enum type if you want to persist it differently.

**Comment by liudaomanbu** [comment] 2018-02-07 08:13
Thank you for your answer.

> The issue you describe does not reproduce against current Ebean. You will need to create a test case that reproduces the issue you claim.

This quesion happened in my enterprise project,it's an older version.
For the latest version, I just downloaded the code for the code comparison of these classes, not actually reproduces the issue in the latest version.

Now,I built a new project to test the latest version of the bug.
Then i found that the latest version has been fixed this bug in method  of DefaultTypeManager.addEnumType(ScalarType<?> scalarType, Class<? extends Enum> enumClass).
```
Set<Class<?>> mappedClasses = new HashSet<>();
    for (Object value : EnumSet.allOf(enumClass).toArray()) {
      mappedClasses.add(value.getClass());
    }
    for (Class<?> cls : mappedClasses) {
      typeMap.put(cls, scalarType);
    }
```
The method do the work that register all anonymous Class to typeMap.
I missed this new method in comparing the code.
I'm sorry.

> It is not recommended to "cross post" - put more than one question / issue into a single ticket is bad form. In this case I'll answer this with ... No, we don't allow people to map a single Enum multiple ways. The reason is that we then are unable to bind by type and can only bind by path and type ... which is too big a limitation on findNative and other binding that doesn't know about property path.

I think that maybe we can determine which ScalarType to use by result object class?
If keep this design,i think should throw Exception in initialization.
It can helps the programmer to determine the position of the problem faster.

**Comment by rbygrave** [comment] 2018-02-13 23:42
I have logged #1259 ... to address the issue of mapping a single Enum to both ORDINAL and STRING which we don't support and don't really want to support in order to keep Enum binding for places we don't have the `property path` like findNative(), RawSql etc.

For this issue, we can say it was fixed in some version - not a bug in current version so I'll close it.

Thanks, Rob.

**Closed by rbygrave** 2018-02-13 23:42 UTC
