### ISSUE TITLE
Postgres - Use NO KEY with FOR UPDATE clauses with Postgres

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#2089] opened 2020-10-22 03:31 UTC
From discussion: 

Hi! I wonder, does Ebean has plans to implement a following feature:
postgres has an FOR NO KEY UPDATE option for explicit locking, which can provide substantial performance benefits compared to FOR UPDATE. It would be nice to have corresponding option in Ebean.
There is similar request for hibernate: https://hibernate.atlassian.net/browse/HHH-13135. I couldn't find anything similar in Ebean issues on Github.

Thanks!

Best regards,
Arsentii.

---

Note the test case for HHH-13135 is:
https://github.com/alostale/hibernate-test-case-templates/blob/locking/orm/hibernate-orm-5/src/test/java/org/hibernate/bugs/AggressivePessimisticWriteTestCase.java

> FOR NO KEY UPDATE option for explicit locking

I did not know about this behaviour and yes I'm surprised by the behaviour of the test case / Postgres here. Being an ex-Oracle guy I was not expecting that behaviour with Postgres so I am reading and thinking about this for the first time.

What I have in my mind is pondering why would we simply not use FOR NO KEY UPDATE rather than FOR UPDATE.  As in, if we always use FOR NO KEY UPDATE when would we not want to do that but instead use FOR UPDATE ?  When do we want to have the "insert into another table using the foreign key" actually wait for the key locked by FOR UPDATE? With Oracle we would not so why would we want this behaviour with Postgres?  

Hmmm.

Cheers, Rob.

**Comment by rbygrave** [comment] 2020-10-22 03:35
Also refer to: 
https://discourse.hibernate.org/t/too-aggressive-pessimistic-write-lock-in-postgresql/1824
https://github.com/alostale/hibernate-test-case-templates/blob/locking/orm/hibernate-orm-5/src/test/java/org/hibernate/bugs/AggressivePessimisticWriteTestCase.java

https://code.djangoproject.com/ticket/30375
https://dba.stackexchange.com/questions/188169/select-for-update-locking-other-tables-in-postgresql

The summary is that this comes down to whether we are row locking with the thinking that the **_Primary key can change_** or whether we are row locking with the thinking that the **_Primary key is not changing_** 

Now with Ebean we are not expecting the primary key to change.  Ebean will NOT generate DML that updates the primary key column.  That does not preclude developers using raw SQL update statements that change the primary key of course but it would not be expected or common.

**Comment by rbygrave** [comment] 2020-10-22 03:44
Is there anyone out there who thinks we should not merge PR - https://github.com/ebean-orm/ebean/pull/2090 ?

**Comment by jnehlmeier** [comment] 2020-10-22 15:12
Given that the new lock behavior is weaker, I would probably provide some sort of option to either activate the new behavior or restore the old behavior (depends on whether or not you believe developers read change logs and recognize the behavior change :-)).

I think updating primary keys can happen if they are not the usual single column autoincrement / uuid primary key but instead a natural key, e.g. an order number or passport number.

**Comment by rbygrave** [comment] 2020-10-22 20:06
>  you believe developers read change logs and recognize the behavior change

People who don't watch the project and choose to not participate have delegated the decision making to the 80 odd people that do watch the project. I see it as a natural filter that the people watching the project have a higher interest in all things database etc (the people much more likely to have an opinion).

So we might choose to have a feature toggle but I think we should be comfortable that what is good enough for the people participating should be good enough for everyone in terms of decision making.

> I think updating primary keys can happen if ...

I must admit I'm in the "never update a PK" camp as in never ever. The real world usually always has a shade of grey to it but I'd really struggle to agree to update a PK and I don't recall _ever_ seeing it in the real world ever (in 30 years).  I feel it's more that in the real world you can't ever update a PK even if you wanted to for some interesting reason - we instead have to logically "void" "invalidate" "soft delete" instead. 

A PK update cascading to all FK references sounds bad but then you add on the implications to materialised views, any reporting databases etc.

Hmmm.

**Comment by arsentiikaptsan** [comment] 2020-10-24 01:35
I think there are legitimate cases when we need a FOR UPDATE locking instead of a weaker FOR NO KEY UPDATE. I am actually is working on a project where, I believe, this would be useful. It's quite common scenario: I have one to many relationship, let's call it pull-request 1-n comment, both can be open or closed. I need to enforce a following constraint at the application level: new comments can't be added to closed issue and issue can't be closed if there are any open comments. The problem is very similar to what postgres internally does to enforce foreign key constraint. One possible solution is:
1) before adding new comments to an issue transaction has to SELECT ... FOR KEY SHARE (the weakest row lock) on that issue, check if it is open and finally save new comment;
2) before closing an issue transaction has to SELECT ... FOR UPDATE (the strongest row lock) it, check if there are any open comments (notice, new ones couldn't be added in the meantime) and if none, mark issue as soft deleted;
3) when updating issue's columns other than isDeleted flag, transactions should acquire FOR NO KEY UPDATE either by explicitly requesting it in SELECT or by using UPDATE on non-unique columns. Such operations would not block transactions, that add new comments to the issue.
If only FOR NO KEY UPDATE mode is available, there is no way to allow operations 1 and 3 to occur simultaneously. To do that we need all 3 of them: FOR UPDATE, FOR NO KEY UPDATE and FOR KEY SHARE. There is also FOR SHARE row lock in postgres.

**Comment by arsentiikaptsan** [comment] 2020-10-24 03:33
In my opinion It would be nice to have all 4 lock modes in Ebean, so cases like that can be implemented more efficiently. However leaving only FOR NO KEY UPDATE as default, I think, is also ok, since situations, where you need to update primary key (especially using SELECT ... FOR UPDATE instead of simple UPDATE) are extremely rear.

**Comment by rbygrave** [comment] 2020-11-20 01:48
Thanks for all the feedback and thoughts people.  I have updated the PR and we have the configuration option via PlatformConfig.lockWithKey.

e.g. To set on via properties
```
## new behaviour with NO KEY
ebean.lockWithKey=false

## existing behaviour
ebean.lockWithKey=true

```
Or via: 
```
databaseConfig.getPlatformConfig().setLockWithKey(true);
```
Noting that although this is on PlatformConfig this property only applies to Postgres.



> ... whether or not you believe developers read change logs and recognize the behavior change 

Nice reminder :)   What I think the best plan is to initially default to the current behaviour.  I'll turn on the new behaviour for apps we have that make a lot of use of `FOR UPDATE`.  

In a few months time I'll likely propose that we change the default to use `NO KEY` and see how we feel about it then.


> In my opinion It would be nice to have all 4 lock modes in Ebean

Yes, interesting case.  We start desiring more explicit control like `forUpdate(<keyOption>, <waitOption>)` ... to support the 12 different combinations where:

`<keyOption>` is one of `{ UPDATE | NO KEY UPDATE | SHARE | KEY SHARE }`
`<waitOption>` is `NOWAIT | SKIP LOCKED`  or nothing

Or:
`forUpdate(<keyOption>)`
`forUpdateNoWait(<keyOption>)`
`forUpdateSkipLocked(<keyOption>)`

We need to ponder this a little more but we don't really have a nice solution for the case where people need that level of control (so as I see it we have an issue here).

Cheers, Rob.

**Closed** 2020-11-24 09:02 UTC
Labels: enhancement

**Comment by rbygrave** [comment] 2020-11-24 11:01
See also https://github.com/ebean-orm/ebean/pull/2113
