### ISSUE TITLE
Q: @DbArray returns empty collection rather than null?

### ISSUE THREAD

**Issue by pgilmore** [ebean-orm/ebean#2019] opened 2020-06-09 13:48 UTC
Not sure if this is a bug or works as intended. 

But even if a DBArray is set to nullable and the value stored is null the fetched object will contain an empty collection. 

The use case for null could be: 
```kotlin
when {
   dbArray.isEmpty() -> CustomerHasAsweredButPreferedNotToSay
   dbArray.isNotEmpty() -> CustomerHasAnsweredWithValues
   null -> CustomerHasNotAnsweredYet
}
```

If this is the intended behavior a comment in the JavaDoc for the DbArray annotation would be great. 

Thanks and keep up the awesome work! 

## Expected behavior
Setting a DBArray field that is nullable to null should return null on a object fetched from the database
## Actual behavior
Setting a DBArray field that is nullable to null returns an empty collection 

### Steps to reproduce

See CDLLicenseTest for testable example
https://github.com/tobias-/example-gradle-kotlin/tree/db_array_test_nullability

```kotlin
  @Entity
data class CDLLicense(
  @Column(unique = true)
  val licenseNumber: Int,
  val name: String,
  @DbArray
  val licenseTypes: Set<LicenseType> = emptySet(),
  @DbArray
  val endorsements: Set<Endorsement>? = null
) : BaseModel() {
  companion object Find : CDLLicenseFinder()
}

@Test
  fun `Test create and find license with endorsements set to null`() {
    CDLLicense(
      licenseNumber = 7890,
      name = "Patrick Gilmore",
      licenseTypes = setOf(
        LicenseType.C,
        LicenseType.B
      ),
      endorsements = null
    ).save()

    val foundLicense = CDLLicense.findByLicenseNumber(7890)
    assertNotNull(foundLicense)
    assertEquals("Patrick Gilmore", foundLicense.name)
    assertTrue(foundLicense.licenseTypes.containsAll(setOf(LicenseType.C, LicenseType.B)))
    assertNull(foundLicense.endorsements)
  }
```

```console
  org.example.domain.CDLLicenseTest > Test create and find license with endorsements set to null FAILED
    java.lang.AssertionError: Expected value to be null, but was: <[]>.
        at kotlin.test.DefaultAsserter.fail(DefaultAsserter.kt:16)
        at kotlin.test.Asserter$DefaultImpls.assertTrue(Assertions.kt:196)
        at kotlin.test.DefaultAsserter.assertTrue(DefaultAsserter.kt:11)
        at kotlin.test.Asserter$DefaultImpls.assertNull(Assertions.kt:251)
        at kotlin.test.DefaultAsserter.assertNull(DefaultAsserter.kt:11)
        at kotlin.test.AssertionsKt__AssertionsKt.assertNull(Assertions.kt:87)
        at kotlin.test.AssertionsKt.assertNull(Unknown Source)
        at kotlin.test.AssertionsKt__AssertionsKt.assertNull$default(Assertions.kt:86)
        at kotlin.test.AssertionsKt.assertNull$default(Unknown Source)
        at org.example.domain.CDLLicenseTest.Test create and find license with endorsements set to null(CDLLicenseTest.kt:66)

```

**Comment by rbygrave** [comment] 2020-06-12 01:23
See https://github.com/ebean-orm/ebean/issues/1867

> The expected change / fix
> The change will be to the ebean-agent changing the enhancement for @DbArray to work like @OneToMany etc such that the collection is always initialised on demand effectively **_meaning that the DbArray collection is never null to code that uses it_** (as we intercept the GETFIELD call and initialise it on demand).


So wrt this issue:
>  should return null on a object fetched from the database

A `@DbArray` in code returns an empty collection to be consistent with the other collections `@OneToMany` etc 

So yes this is intended behaviour.

**Comment by rbygrave** [comment] 2020-06-12 01:28
I'll close this assuming this answers the question completely.

**Closed by rbygrave** 2020-06-12 01:28 UTC
Labels: question

**Comment by bkempe** [comment] 2020-12-16 21:31
Does this mean that loading and saving a record may turn a `NULL` into a `[]` column value in the DB?

**Comment by rbygrave** [comment] 2022-10-03 20:31
Unfortunately @bkempe I somehow missed your question.  

It seems that might be the case but I am not sure yet. I don't think we have a test case for this but it looks like someone might have hit an issue. We may shortly get to this issue around `NULL` here / investigate and produce some tests that might be missing.
