### ISSUE TITLE
Can you add support for OneToMany/ManyToOne/OneToOne JoinTables?

### ISSUE THREAD

**Issue by cao19920425** [ebean-orm/ebean#1137] opened 2017-09-15 14:16 UTC
http://docs.oracle.com/javaee/7/api/javax/persistence/JoinTable.html

the javaDoc content:

> A join table is typically used in the mapping of many-to-many and unidirectional one-to-many associations. It may also be used to map bidirectional many-to-one/one-to-many associations, unidirectional many-to-one relationships, and one-to-one associations (both bidirectional and unidirectional).

so i think that the support for OneToMany/ManyToOne/OneToOne is Conform to the jpa.

Can you add support for OneToMany/ManyToOne/OneToOne JoinTables?
Do you have a plan to add the support?

I think the support is important.
Because that the association relationship stored in a separate table has two advantages;
Firstly,this design do not need to modify POJO table columns.
Secondly,This design will be very simple to modify the relationship.

**Comment by rbygrave** [comment] 2017-09-15 22:44
This looks like a duplicate of https://github.com/ebean-orm/ebean/issues/123

**Comment by cao19920425** [comment] 2017-09-16 05:41
Let me see the #123 .
Yes,this issue and #123 are the same,buf this issue add the ManyToOne and OneToOne.
Oh,the #123 opened on 30 Apr 2014 ,now is 2017-9-16.
You do not have a plan to add the support?
The support is very hard?

**Comment by rbygrave** [comment] 2017-09-27 07:58
Closing as duplicate.

> You do not have a plan to add the support?

Yes, it is an open ticket. It is a matter of time and priorities (there have always been higher priorities to resolve first).  I don't know how hard it is yet no.

**Closed by rbygrave** 2017-09-27 07:58 UTC
