### ISSUE TITLE
Where Raw clause with subquery generate wrong column names in sql query 

### ISSUE THREAD

**Issue by buchtajz** [ebean-orm/ebean#3003] opened 2023-03-21 21:48 UTC
## Expected behavior
Not change column names (aliases) in subquery.

## Actual behavior
Adds t0. prefix to column names when there is column with same name in parent query.

### Steps to reproduce

```java
  DB.find(Customer.class)
      .select("name")
      .where()
      .raw("id in (select c.id as id from o_customer c)")
      .findList();
```
generates invalid query

`select t0.id, t0.name from o_customer t0 where t0.id in (select c.id as t0.id from o_customer c)` 

and throws exception

```console
  Syntax error in SQL statement "select t0.id, t0.name from o_customer t0 where t0.id in (select c.id as t0[*].id from o_customer c)"; expected ",, FROM, WHERE, GROUP BY, HAVING, WINDOW, QUALIFY, INTERSECT, UNION, EXCEPT, MINUS, ORDER BY, OFFSET, FETCH, LIMIT, FOR, ,, )";
    SQL statement:
    select t0.id, t0.name from o_customer t0 where t0.id in (select c.id as t0.id from o_customer c) [42001-214] Bind values:[null] Query was:select t0.id, t0.name from o_customer t0 where t0.id in (select c.id as t0.id from o_customer c)
```
It's not limited only to id column and this simple example. Subquery can be complex CTE query, with many column aliases.

**Comment by buchtajz** [comment] 2023-03-22 10:06
- Subqueries are dynamic, written by customers (individually correct)
- they can be complex CTE queries - bug appears at CTE too 
   `WITH some_cte AS (SELECT p.xyz AS firstname FROM b JOIN p ... ), ...`
   is generated as 
   `WITH some_cte AS (SELECT p.xyz AS t0.firstname FROM b JOIN p ... ), ...`
  when there is conflict in column names in t0 table (t0.firstname exists), so query is invalid and throws exception

**Comment by rbygrave** [comment] 2023-03-22 10:47
> Subqueries are dynamic, written by customers (individually correct)

What do you mean here?  Do you mean a customer sends a String with SQL in it via some Rest API and the application just includes it in the query?

**Comment by buchtajz** [comment] 2023-03-22 11:17
Not so crazy security maddnes :)

It's not public available. Customer, or better some emloyees, can create sql query in company private application instance. 

Security is not problem there. This is part of bussines process modelling.

**Comment by rbygrave** [comment] 2023-03-22 11:22
Are you saying that you are unable to modify the SQL that makes up the subquery?  

That there is some code that does string concatenation to build the string expression that goes into the raw() expression?

**Comment by buchtajz** [comment] 2023-03-22 11:40
> That there is some code that does string concatenation to build the string expression that goes into the raw() expression?

For this use case, yes.

But what about this (yes, this example is nonsense, but problem exist):
```Java
 DB.find(Customer.class)
      .select("name")
      .where()
      .raw("id in (select id from o_order)")
      .findList();

```
generated as 
`select t0.id, t0.name from o_customer t0 where t0.id in (select t0.id from o_order);`

There can be workaround, run subquery separately and bind ids as parameter. But subqueries should not be modified this way in principle i think. Or is there some request for it?

**Comment by rbygrave** [comment] 2023-03-22 12:02
> this example is nonsense

This is the problem in terms of determining the correct way to move forward. This example is poor because it is easily resolved by not using the property name in the subquery.

raw expressions are EXPECTED to parse for and replace logical property names. 

That is, the behaviour is EXPECTED and not a bug.

>  but problem exist

We need to see the "real" problem to understand what the best path/solution for it is. Perhaps it should use findNative() perhaps RawSql or perhaps we can look to enhance raw expressions in some way ... but we need to understand the "real" problem to do that.

With the example given the answer is ... _"write the subquery without using unqualified bean property paths"_ 

e.g.:

```java
.raw("id in (select o.id from o_order o)") // Fixed
```

**Comment by buchtajz** [comment] 2023-03-22 13:04
This looks good.

Or something like
```Java
String someSubQuery = "..."; // I can't easily fix or modify this sub-query for some reason

.inRawUnparsedQuery("id", someSubquery)

```

Peoples creating subqueries are not developers. They are sql power users, but in some cases, when used as subquery, there is SQLException. So they call us, and we are able to modify subquery to working state. But it's not the way in general.

There can be something like this (part of real subquery last time used):

```SQL
WITH  relevant_people AS (
    SELECT p.id,
           p.firstname AS firstname,
           p.lastname AS lastname
    FROM  people_roles pr
          JOIN people p ON pr.person_id = p.id AND pr.role_id IN (11,16,18,80,108) AND p.id NOT IN (18,3) AND p.employed_to IS NULL--konstrukér,technolog,normovač, programátor,Konstrukce a Technologie
    GROUP BY p.id
)     ,
     daily_at_work AS 
 ....  -- (many CTE)
 SELECT w.id FROM .....
```

and generated sql has bad syntax

`p.firstname as t0.firstname`

Yes, correction of this was primitive, column aliases was unnecessary. But we would like to eliminate the need for such modifications in future.

**Comment by rbygrave** [comment] 2023-03-23 06:32
> Or something like ...

Right, I understand. I'll have a look at the internals and see what a `inRawUnparsedQuery()` could look like.

**Comment by rbygrave** [comment] 2023-03-25 02:36
PR that includes support for raw SQL subqueries - https://github.com/ebean-orm/ebean/pull/3008

See: https://github.com/ebean-orm/ebean/pull/3008/commits/79fd689e9a84455da9b4760def06ed4c28085fd8#diff-22c2f06e5abe775b9f48a758807a50d686978f6523467d12a19acb46e0925b0aR219-R223

So `inRawUnparsedQuery()` is called `inSubQuery()` + has the option of taking bind values + has variations for notIn, eq, ne, gt, ge, lt, le, exists and notExists.

**Comment by buchtajz** [comment] 2023-03-25 17:43
Thank you very much, Rob

**Comment by rbygrave** [comment] 2023-03-25 19:33
Just for tracking, lets keep it open until we have released a version with the fix / feature.

**Closed** 2023-04-06 03:25 UTC
