### ISSUE TITLE
Ebean agent conflicts with kotlin data classes by wiring with `equals`

### ISSUE THREAD

**Issue by soberich** [ebean-orm/ebean#1676] opened 2019-04-12 15:15 UTC
Hi, 
unfortunately ebean-agent probably doing somthing which it should not.

given 
```kotlin
abstract class SimpleIdentity<T : Serializable>: Identity<T>() {
    final override fun equals(other: Any?) = super.equals(other)
    final override fun hashCode() = super.hashCode()
}
```
when
```kotlin
fun main() {
    println(Employee(1, "2", "2")==(Employee(1, "2", "2")))
}
```

we get
```console
Exception in thread "main" java.lang.VerifyError: class com.example.Employee overrides final method equals.(Ljava/lang/Object;)Z
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.example.MainKt.main(main.kt:5)
	at com.example.MainKt.main(main.kt)
```

code attached.

[ebean-agent-issue.zip](https://github.com/ebean-orm/ebean/files/3073925/ebean-agent-issue.zip)

##### Run it inside Intellij IDEA

If we remove `Entity` annotation so ebean does not modify class - it's ok.
tried with several gradle and jvm versions.
Java 1.8 does not work for sure.

**Comment by soberich** [comment] 2019-04-12 15:33
I understand the reason. Is there some workaround from ebean's side? Or something you could implement?
The solution for use would be to have delegated to ` fun equals(other: Any?) = super.equals(other)` equals in every entity. But maybe some workaround you may implement in agent?

**Comment by soberich** [comment] 2019-04-13 02:46
Also here is what i got if put `MappedSuperclass` on that `SimpleEntity`
```console
 e: Projects/mn_3/build/tmp/kapt3/stubs/main/com/example/domain/model/RecordCollection.java:7: error: Error generating query beans: java.lang.ClassCastException: com.sun.tools.javac.code.Symbol$TypeVariableSymbol cannot be cast to javax.lang.model.element.TypeElement
 public final class RecordCollection extends com.example.domain.model.base.SimpleGeneratedIdentityOf<java.lang.Long> {
              ^
 e: Projects/mn_3/build/tmp/kapt3/stubs/main/com/example/domain/model/Employee.java:9: error: Error generating query beans: java.lang.ClassCastException: com.sun.tools.javac.code.Symbol$TypeVariableSymbol cannot be cast to javax.lang.model.element.TypeElement
 public final class Employee extends com.example.domain.model.base.SimpleGeneratedIdentityOf<java.lang.Long> {
              ^
```

**Comment by rbygrave** [comment] 2019-04-18 04:53
```kt
override fun hashCode() = 0
```
As I see it this is really in the area of ... **not good**  / **not ok**  ??  ... as in are you really really really sure on that?

**Comment by rbygrave** [comment] 2019-04-18 04:56
There are no tests?  `gradle test` passes ??

**Comment by rbygrave** [comment] 2019-04-18 04:57
```kotlin
    @Column(nullable = false)
    val name                : String,
```
Note that Ebean knowns about kotlin nullable types.  We don't need `@Column(nullable = false)` in cases like this where the type is a non-nullable type.

**Comment by rbygrave** [comment] 2019-04-18 05:00
Hmmm, this gradle project looks like it depends on gradle 5 or something?  No explicit gradle version defined for the build.

**Comment by rbygrave** [comment] 2019-04-24 02:32
@soberich  This gradle.build is broken for me.  Can you update it with an explicit gradle version to use or something such that I can run it?

**Comment by rbygrave** [comment] 2019-04-29 04:25
1. `gradle wrapper --gradle-version 5.0`
2. Updated `build.gradle` with

```
tasks.withType(JavaCompile) {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).all {
    kotlinOptions {
        jvmTarget = "1.8"
        apiVersion = "1.3"
        languageVersion = "1.3"
    }
}
```

All running fine.  Not reproducing the issue.  Running the main method produces:
```
true
true
false

Process finished with exit code 0
```

Can you review again and re-supply as failing test @soberich ?

**Comment by rbygrave** [comment] 2019-04-29 04:54
Note:
```
override fun hashCode() = 0
```
... again, I'd have to stress this is as I see it really bad for use with Maps and Sets. 

Additionally, Ebean does a good job with the `equals` and `hashCode` implementation to the point that it is as good as we can get in my opinion. Perhaps not everyone agrees but in my opinion you are not going to improve on the equals and hashCode implementation that is produced by Ebean enhancement.

**Comment by rbygrave** [comment] 2019-04-29 07:58
Alternative code 
```kotlin
interface WithIdentity<T> {
  fun identity() : T
}
```
```kotlin
@MappedSuperclass
abstract class BaseDomain : Model(), WithIdentity<Long> {

  @Id
  @GeneratedValue
  val id: Long = 0

  @Version
  var version: Long = 0

  override fun identity(): Long {
    return id
  }
}

@MappedSuperclass
abstract class BaseUuidDomain : Model(), WithIdentity<UUID> {

  @Id
  @GeneratedValue
  lateinit var id: UUID

  @Version
  var version: Long = 0

  override fun identity(): UUID {
    return id
  }
}

@MappedSuperclass
abstract class AuditDomain : BaseDomain() {

    @WhoCreated
    //@Column(nullable = false, updatable = false)
    val createdBy           : String? = null

    @WhenCreated
    //@Column(nullable = false, updatable = false)
    val createdDate         : Instant = Instant.now()

    @WhoModified @Length(50)
    //@Column(nullable = false, length = 50)
    val lastModifiedBy      : String? = null

    @WhenModified
    //@Column(nullable = false)
    val lastModifiedDate    : Instant = Instant.now()
}

```

**Notes**:
- Primitives are non-nullable ... e.g. `var version: Long = 0` is implicitly `@NotNull`
- Ebean treats Kotlin Non-nullable types as not nullable
- `@Who...` and `@When...` are non-nullable

**Comment by rbygrave** [comment] 2019-04-29 08:03
```kotlin
@Entity
class Employee(
    //@Column(nullable = false)
    val name                : String,

    @Column(unique = true)
    val email               : String

) : BaseDomain() {

    @OneToMany(cascade = [ALL], orphanRemoval = true)
    lateinit var records: List<RecordCollection>

  companion object Find : EmployeeFinder()
}
```
Notes:
- name and email ... are kotlin non-nullable types so Ebean treats them as non-nullable 
- We don't have `id` in the constructor ...

```kotlin
    val e0 = Employee("2", "2@foo.com")
    e0.save();

    val e1 = Employee("3", "3@foo.com")
    e1.save()

    println(e0.hashCode())  // 1
    println(e1.hashCode())  // 2

    assertThat(e0).isNotEqualTo(e1)
    assertThat(e0.id).isNotEqualTo(e1.id)

    // Use of reference bean ...
    val e0Ref = Employee.ref(e0.id)
    assertThat(e0Ref).isEqualTo(e0)
    assertThat(e0Ref).isNotSameAs(e0)

    // IF id is 'var' rather than 'val' we could do ...
    val e0InMemory = Employee("2", "2@foo.com")
    e0InMemory.id = e0.id
    assertThat(e0).isEqualTo(e0InMemory)

    val e0InMemory2 = Employee("2", "2@foo.com")
    assertThat(e0).isNotEqualTo(e0InMemory2)

```

**Comment by rbygrave** [comment] 2019-04-29 08:09
## Alternative constructor option

We can include the annotations in the constructor but this can get a bit "messy" ...

```kotlin
@Entity
@Cache(naturalKey = ["name"])
@History
class Project(
    @Column(unique = true)
    val name                : String
) : BaseDomain()
```

Alternatively we can do ...

```kotlin
@Entity
@Cache(naturalKey = ["name"])
@History
class Project(name: String) : BaseDomain() {

  @Column(unique = true, length = 150)
  val name: String = name

}
```
I personally kind of like this style for entity beans where the constructor is easier to read (without the mapping annotations getting in the way).  Note that `name` is a kotlin non-nullable type so we don't need to explicitly state that. 

```sql
create table project (
  id                            bigint auto_increment not null,
  name                          varchar(150) not null,
  version                       bigint not null,
  constraint uq_project_name unique (name),
  constraint pk_project primary key (id)
);

```

**Comment by rbygrave** [comment] 2019-04-29 08:14
### Kotlin non-nullable types

Ebean knows about kotlin non-nullable types so we don't need to specify any of the `nullable = false` or `optional = false` specified here.

```kotlin
@Entity
data class RecordCollection(

  //@Column(nullable = false) ... non null type
  val year: Year,

  //@Column(nullable = false) ... non null type
  val month: Month,

  @ManyToOne // (optional = false) ... non null type
  val project: Project,

  @ManyToOne //(optional = false) ... non null type
  val employee: Employee

) : BaseDomain() {

  @OneToMany(cascade = [ALL], orphanRemoval = true)
  lateinit var records: List<Record>
}
```

```sql
create table record (
  id                            bigint auto_increment not null,
  record_collection_id          bigint not null,
  date                          date not null,
  type                          varchar(255) not null,
  hours_submitted               decimal(3,1) not null,
  desc                          varchar(255),
  version                       bigint not null,
  created_by                    varchar(255) not null,
  created_date                  timestamp not null,
  last_modified_by              varchar(50) not null,
  last_modified_date            timestamp not null,
  constraint pk_record primary key (id)
);
```

**Comment by rbygrave** [comment] 2019-04-29 08:23
## lateinit on `@OneToMany`

Nice spotting here.  Ebean enhancement always ensures `@OneToMany` and `@ManyToMany` are returned as non-null so use of `lateinit` here is cool.

```kotlin
  @OneToMany(cascade = [ALL], orphanRemoval = true)
  lateinit var records: List<Record>
```

Note that if alternatively if the code was:
```kotlin
  @OneToMany(cascade = [ALL], orphanRemoval = true)
  var records: List<Record> = mutableListOf()
```
Ebean enhancement actually removes the 'eager' creation the the list ... so the actual list is only created on demand (saving a little bit of cost when we new up beans and then don't use the collections).

**Comment by rbygrave** [comment] 2019-04-29 08:26
## lateinit with Who and When properties

If we are ok using `var` rather than `val` we can use `lateinit` on the Who and Where properties like:

```kotlin
@MappedSuperclass
abstract class AuditDomain : BaseDomain() {

  @WhoCreated @Length(50)
  lateinit var createdBy: String

  @WhenCreated
  lateinit var createdDate: Instant

  @WhoModified @Length(50)
  lateinit var lastModifiedBy: String

  @WhenModified
  lateinit var lastModifiedDate: Instant
}
```

**Comment by soberich** [comment] 2019-05-02 23:23
Thank you, I will answer soon.

**Comment by soberich** [comment] 2019-05-05 14:04
@rbygrave a short answer in between 
Is this actual as for now https://archive-avaje-org.github.io/equals.html
regarding "vanilla" particularly?

**Comment by soberich** [comment] 2019-05-05 14:10
@rbygrave BTW the code I submitted was obscured version of code ported from real java and hibernate project. The project followed this advice for example https://vladmihalcea.com/the-best-way-to-implement-equals-hashcode-and-tostring-with-jpa-and-hibernate/
Just to give some context.

**Comment by rbygrave** [comment] 2019-05-07 09:57
Thanks (that advice is not good).

> Both natural identifiers and database-agnostic UUIDs have the luxury of being known when the entity gets persisted. For this reason, it is safe to use them in the equals and hashCode implementation:

Unfortunately this statement is misleading - isn't actually correct **enough**.  equals/hashcode **should** be stable when it is **used**.  That means that if you use equals/hashcode before a bean is persisted then it needs to be stable from that point onwards.  As soon as you put beans into a Set you are using hashCode and equals.

That is, `equals/hashCode` is used internally by Sets so as soon as we put beans into a set we are using equals/hashCode.  This is especially problematic for users of Hibernate which gives Set better persistence semantics than List for collection mapping.  So hibernate users tend to prefer the use of Set over List for mapping collections and are implicitly using hashCode/equals a lot!!  

Regarding this:
```java
@Override
    public int hashCode() {
        return 31;
    }
```
That is a very surprising (because he usually has good advice) but a fixed hashCode function like the above is a terrible idea if we use Set (and with Hibernate people are using Set a lot).  Having a good hashCode function is important with regards the internal mechanisms that spread entries across the tables/buckets.  

"Put 100,000 entries into a Set and all of them have the same hashCode()" == Bad because all the entries go into the same table/bucket.

The actual enhancement implementation we use with Ebean comes from a Hibernate forum topic / Gerry Power.

Look through the forum discussion for Gerry Power's suggestion here: 
https://forum.hibernate.org/viewtopic.php?t=928172&postdays=0&postorder=asc&start=0&sid=e34c88ebf24b90219be45fbc81752084

See also: https://archive-avaje-org.github.io/equals.html

**Comment by rbygrave** [comment] 2019-06-14 07:30
@soberich  ... I'll close this for now.  We can reopen when we have a failing test case or more information.

Thanks, Rob.

**Closed by rbygrave** 2019-06-14 07:30 UTC
Labels: needs work, on hold
