### ISSUE TITLE
DDL script is incorrectly generated for an enum in an embedded class

### ISSUE THREAD

**Issue by igortwago** [ebean-orm/ebean#872] opened 2016-11-08 13:17 UTC
[test-bug-app.zip](https://github.com/ebean-orm/ebean/files/578221/test-bug-app.zip)

When DDL is generated for an enum like this 
```java
public enum Status {
	@EnumValue("O")
	Open,
	
	@EnumValue("C")
	Closed;
	
}
```
which is used in an embeddable class like this 
```java
@Embeddable
public class IntInfo {

	public String name;
	
	public Status status;
	
}

```
and the status property is overridden in embedding class like this 
```java
@Entity
public class Company extends Model {

    @Id
    public Integer id;
    
    @Embedded
    @AttributeOverrides({ @AttributeOverride(name = "name", column = @Column(name = "company_name")),
    	@AttributeOverride(name = "status", column = @Column(name = "company_status"))})
    public IntInfo intInfo;
	
}
```
incorrect DDL is generated
```SQL
create table company (
  id                            integer not null,
  company_name                  varchar(255),
  company_status                varchar(1),
  constraint ck_company_company_status check (status in ('C','O')),
  constraint pk_company primary key (id)
);
```
This script has an incorrect name for the company_status column in check function 
```SQL
check (status in ('C','O')
```
In attempt to run this script on H2 next error message will be shown 
```
We got the following error: Column "STATUS" not found; SQL statement: create table company ( id integer not null, company_name varchar(255), company_status varchar(1), constraint ck_company_company_status check (status in ('C','O')), constraint pk_company primary key (id) ) [42122-192] [ERROR:42122, SQLSTATE:42S22], while trying to run this SQL script:
```
The play project with a reproducible error can be found in the attachment. 
To run this project, run in sbt console run command and open http://localhost:9000/ url.
```
[test-bug-app] $ run
```

**Comment by rbygrave** [comment] 2016-11-15 10:25
I see the linked zip app references Ebean version 7.6.1 ... and I am not able to reproduce in the latest version of Ebean.

```java
@Entity
public class EPerson {

  @Id
  Long id;
  ...
  @Embedded
  @AttributeOverrides({
    @AttributeOverride(name="city", column = @Column(name="addr_city")),
    @AttributeOverride(name="status", column = @Column(name="addr_status"))
  })
  EAddress address;
```

```sql
create table eperson (
  id                            bigint auto_increment not null,
  name                          varchar(255),
  notes                         varchar(255),
  street                        varchar(255),
  suburb                        varchar(255),
  addr_city                     varchar(255),
  addr_status                   varchar(3),
  version                       bigint not null,
  constraint ck_eperson_addr_status check ( addr_status in ('ONE','TWO')),
  constraint pk_eperson primary key (id)
);
``` 
Can you try against the latest version of Ebean?

**Comment by igortwago** [comment] 2016-11-21 07:51
Yes, you are right, after upgrading ebean version this problem is not reproducible any more.

**Comment by rbygrave** [comment] 2016-11-21 08:00
Great.  I'll close this as fixed. 

Cheers, Rob.

**Closed by rbygrave** 2016-11-21 08:00 UTC
Labels: bug
