### ISSUE TITLE
Update statement on (Jackson) ObjectNode fields throws "javax.persistence.PersistenceException: No ScalarType registered for class"

### ISSUE THREAD

**Issue by madskaddie** [ebean-orm/ebean#2117] opened 2020-11-25 15:42 UTC
## Expected behavior
I expected that update statements would work the same as setting the fields and calling the `database#update(bean)`

## Actual behavior
I got an exception with a json field. I can work around (using H2, not sure postgres would like) by calling the `node#toString()` and by using setters (which I would really like to avoid). With setters the generated query (H2):
```sql
update some_table set input_data=?, async_state=?, async_state_changed_at=?, async_output_data=? where id=?; -- bind({"foo":"bar"},TERMINATED,2020-11-25T15:37:53.869001,{"someField":"6041b523-80e3-4178-a34a-5bb665331...,6041b523-80e3-4178-a34a-5bb665331b71)
```

(Because of the setter, now the input_data field also is sent, which is also an objectnode)

### Steps to reproduce

```java
class SomeEntity {
    // ....
    @Enumerated(EnumType.STRING)
    @Column(name = "async_state", nullable = false)
    private SimulationRequestAsyncState asyncState;

    @Column(name = "async_state_changed_at", nullable = false)
    private LocalDateTime asyncStateChangedAt;

    @DbJson
    @Column(name = "async_output_data", nullable = true)
    private JsonNode asyncOutputData;
}

// database update method:
   @Override
    public int updateStateAndData(Database database, UUID id, SimulationRequestAsyncState state,
                ObjectNode outputData) {
            var query = new QSomeEntity(database);
            var update = query.id.eq(id).asUpdate().set("asyncState", state)
                    .set("asyncOutputData", outputData)
                    .set("asyncStateChangedAt", LocalDateTime.now(zoneId));
            int nrows = update.update();
            return nrows;
```

calling the method with non null inputs, yields the following stacktrace:

`javax.persistence.PersistenceException: No ScalarType registered for class com.fasterxml.jackson.databind.node.ObjectNode
	at io.ebeaninternal.server.persist.Binder.getScalarType(Binder.java:191)
	at io.ebeaninternal.server.persist.Binder.bindObject(Binder.java:216)
	at io.ebeaninternal.server.querydefn.OrmUpdateProperties$SimpleValue.bind(OrmUpdateProperties.java:73)
	at io.ebeaninternal.server.querydefn.OrmUpdateProperties.bind(OrmUpdateProperties.java:164)
	at io.ebeaninternal.server.query.CQueryPredicates.bind(CQueryPredicates.java:127)
	at io.ebeaninternal.server.query.CQueryPredicates.bind(CQueryPredicates.java:119)
	at io.ebeaninternal.server.query.CQueryUpdate.execute(CQueryUpdate.java:91)
	at io.ebeaninternal.server.query.CQueryEngine.executeUpdate(CQueryEngine.java:81)
	at io.ebeaninternal.server.query.CQueryEngine.update(CQueryEngine.java:76)
	at io.ebeaninternal.server.query.DefaultOrmQueryEngine.update(DefaultOrmQueryEngine.java:76)
	at io.ebeaninternal.server.core.OrmQueryRequest.update(OrmQueryRequest.java:394)
	at io.ebeaninternal.server.core.DefaultServer.update(DefaultServer.java:1330)
	at io.ebeaninternal.server.querydefn.DefaultOrmQuery.update(DefaultOrmQuery.java:1477)
	at io.ebeaninternal.server.querydefn.DefaultUpdateQuery.update(DefaultUpdateQuery.java:64)
	at .....updateStateAndData()
`

**Comment by rbygrave** [comment] 2020-11-25 19:21
What happens if we replace the query with a "stateless update" like:

```java
SomeEntity bean  = new SomeEntity();
bean.setId(id);
bean.setAsyncState(state);    
bean.setAsyncOutputData(outputData);
bean.setAsyncStateChangedAt(LocalDateTime.now(zoneId));

database.update(bean);
```

**Comment by madskaddie** [comment] 2020-11-25 23:59
Are you sugesting to fetch the data first, then clone to a new object the part that remains in the same state and update the part

```java
var bean = db.find(SomeEntity.class, id);
var updated = new SomeEntity(id, bean.getInputData(), state, outputData, LocalDateTime.now(zoneId))
db.update(updated)
```

Something like this?

it generates the same query as the "setter" approach but that makes sense:

```sql
update some_table  input_data=?, async_state=?, async_state_changed_at=?, async_output_data=? where id=?; -- bind({"foo":"bar"},TERMINATED,2020-11-25T23:49:32.286951,{"someField":"b92767e8-d780-4f3f-959a-75bc5f916...,b92767e8-d780-4f3f-959a-75bc5f916481)
```


It looks like `UpdateQuery#update()` and `Database#update` code paths don't use the same binding type registry. The first uses the runtime class of the parameter value of the `UpdateQuery.set(String propName,Object value)` method call and the last the definition from the entity field

**Comment by rbygrave** [comment] 2020-11-26 01:38
No. Just update the bean without fetching it.

It is called a stateless update, an update with out fetching the bean first.

**Comment by madskaddie** [comment] 2020-11-26 09:16
Uhm... I'm not sure if I understand the implications of what you mean. From [here](https://ebean.io/docs/architecture/compare-jpa), I understand that ebean has no persistence context, and the bean in question has no relations, just plain scalar data. I expected `new SomeEntity(...)`  gave mean a "clean state", independently from the origin of the parameters. I understand that there may be issues with relation like attributes (One2Many and so on), but that is not this case.

Then `Database` is a "singleton" so between two requests ("units of work"), what is the difference from setting the data from a entity fetched from the database and, lets say, from the request input?

Anyway, I did what I believe that you are suggesting and the generated query is the same but with `null`s bound (which makes sense because in a ORM all fields (except those marked with `updatable=false`) are sent on  update statements. bye bye data :joy:

**Comment by rbygrave** [comment] 2020-12-01 01:42
> is the same but with nulls bound 

No, they should not be.  Only properties set and generated properties are bound in the update set clause. For a property to be set to null it would have been set to null.


> (which makes sense because in a ORM all fields (except those marked with updatable=false) are sent on update statements

No, not in this case.  The entity is enhanced and that means that Ebean knows which fields were set (via setter methods etc) and only the fields that had been set are included in the update.

Refer to TestStatelessUpdate:

This just sets id and name ... so only name included in the update set clause.
https://github.com/ebean-orm/ebean/blob/master/ebean-core/src/test/java/org/tests/update/TestStatelessUpdate.java#L48

This next one sets id, name and description is set to null ... so name and description are included in update set clause.
https://github.com/ebean-orm/ebean/blob/master/ebean-core/src/test/java/org/tests/update/TestStatelessUpdate.java#L67

**Comment by rbygrave** [comment] 2020-12-04 07:42
I'll close this for now.  Re-open if there is more to this. Thanks.

**Closed by rbygrave** 2020-12-04 07:42 UTC

**Comment by madskaddie** [comment] 2020-12-11 17:31
I think the bug got forgotten in the conversation. The key issue is that the update statement is not working. I would really like to avoid calling the setter by using `...asUpdate().set().execute()`  (because I don't wan't the setter to exist at all)

**Comment by rbygrave** [comment] 2021-01-20 10:38
Effectively a duplicate of https://github.com/ebean-orm/ebean/issues/2148 now.
