### ISSUE TITLE
Impossible to overwrite ebean predefined ScalarTypes.

### ISSUE THREAD

**Issue by adrian5632** [ebean-orm/ebean#1677] opened 2019-04-13 01:59 UTC
## Expected behavior
Ebean should use the latest registered ScalarType for given class so that we can use these rather than the predefined ones.

## Actual behavior
Currently when registering a new ScalarType for a class that has one predefined in ebean will have no effect when de/serialising JSON (in my case a new ScalarType for `LocalDate` which would read/write JSON dates in SQL format (currently ebean can only write them as millis - which IMO defeats the purpose of having a local date representation)).

### Steps to reproduce

```kotlin
// This class is placed in the same package as models; picked up automatically and registered but not used:
class ScalarTypeLocalDateAsString() : ScalarTypeLocalDate() {
    override fun writeData(dataOutput: DataOutput, value: LocalDate?) {
        println("writing local date")
        if (value == null) {
            dataOutput.writeBoolean(false)
        } else {
            dataOutput.writeBoolean(true)
            dataOutput.writeUTF(value.toString())
        }
    }

    override fun readData(dataInput: DataInput): LocalDate? {
        if (!dataInput.readBoolean()) {
            return null
        } else {
            return LocalDate.parse(dataInput.readUTF())
        }
    }
}

// Serialise any entity bean with LocalDate field using Ebean.json().toJson() and ebean will use its own ScalarType that it registered with java times...
```

**Comment by rbygrave** [comment] 2019-04-26 01:24
So this is not a bug.  Works as expected.

The problem above is that the ScalarTypeLocalDateAsString above overrides the wrong methods.  It should instead overwrite the `jsonWrite()` method like the below.  (As see the commit associated with this).

```java
  public static class ScalarTypeLocalDateAsString extends ScalarTypeLocalDate {

    @Override
    public LocalDate jsonRead(JsonParser parser) throws IOException {
      return super.jsonRead(parser); // already handles both number and string input
    }

    @Override
    public void jsonWrite(JsonGenerator writer, LocalDate value) throws IOException {
      writer.writeString(value.toString());
    }
  }
```

So we could close this as - not a bug, works as expected.

**Comment by rbygrave** [comment] 2019-04-26 01:27
@adrian5632  ... can you review the above and then maybe close this assuming you are happy with the above comment.  Thanks.  

Note that I'll look to open a separate ticket where the default JSON marshalling of LocalDate should really be in string format (rather than number) and configurable much like `io.ebean.config.JsonConfig.DateTime`.

**Comment by rbygrave** [comment] 2019-04-26 23:18
See also #1684 - Support for configuring ISO8601 or MILLIS format for date types
See also #1686 - Change to ISO8601 format as default (from epoch millis)

**Comment by rbygrave** [comment] 2019-04-29 04:55
Closing.

**Closed by rbygrave** 2019-04-29 04:55 UTC
Labels: question
