### ISSUE TITLE
find() at scale fails to find records... sometimes

### ISSUE THREAD

**Issue by jphui** [ebean-orm/ebean#3080] opened 2023-05-31 00:03 UTC
Hello! Currently working on a large-scale application that uses Ebean to `insert()` ~1M records daily. We are finding that in about 5% of insertions, a `find()` operation will fail to retrieve an existing record and subsequently insert a "duplicate record" into the DB.

## Expected behavior
Ebean's various find methods -- in particular `find(Class, Object)` , `findNative()` , `find(Class).where()...` -- should successfully return a record that exists in the DB all the time.

## Actual behavior
No matter which of the 3 find pathways are used, there are about 5% of cases where Ebean will give a false negative on record retrieval and say that no record exists.

## Questions
In attempting to debug the issue, there are a few questions that we are looking into but would like an insightful eye into

### 1. Caching
Based on some light reading, there appear to be 2 levels of configurable cache with Ebean. We suspect that caching might be interfering with the accuracy of the retrieval operations and are looking to disable it entirely. Are the following operations sufficient to make this happen?

#### L1
`PersistenceContext` appear to be Ebean's wording for L1 caches and are by default at the Transaction level. In order to "disable" L1 caching, the PersistenceContext [needs to be set to QUERY](https://github.com/ebean-orm/ebean/issues/2410).

EDIT:
Found https://github.com/ebean-orm/ebean/issues/237 as another past caching issue where QUERY level solved the issue.

#### L2
Query and Bean caching are both [disabled by default](https://ebean.io/docs/features/l2cache/).

### 2. desync between software and DB layer configuration of Primary Key
This one is going to sound a bit odd:

- our underlying DB has its primary key set to a composite of 4 attributes `{ A , B , C , D }`
  - this CANNOT be changed
- the Ebean software layer has the Bean class set to a composite only 3 of them `{ A , B , C }` , and this composite key has `@Index` and `@Id` annotations set
  - this cannot be easily changed

Does Ebean make use of these annotations in such a way that this desync between the DB and software would cause incorrectly set up Indices that hinder queries?

### 3. silent timeout possibility?
When a query times out, will Ebean silently respond and return `null`? The 5% rate of failure makes this plausible, but the expectation is that Ebean would throw some sort of Exception instead of a graceful exit?

**Comment by rbygrave** [comment] 2023-05-31 02:56
Well this does sound like this operation is inherently racey? Can you show
us what the actual code of this operation is doing including the
demarcation of the transaction(s)?

Can you confirm the database being used, the version of the database and
the isolation level being used and if there is any DB replication lag (e.g.
Aurora).

What makes you think this operation is not inherently racey? That is, what
makes you think that the behaviour observed is not exactly correct given it
sounds like the insert is conditional on the find and this is occurring
under concurrent load?


*> 2 ...  the Bean class set to a composite only 3 of them*

Indeed that sounds very odd and in fact I don't know how that would work
with 1 attribute of the primary key not modelled and included in the
insert. To understand this we might need to know what makes up the primary
key and specifically if any of those attributes are computed or derived in
some way?


*> incorrectly set up Indices that hinder queries?*

I don't understand this question.  Perhaps if you are more explicit about
the primary key and the actual model and the actual insert statement
perhaps ? ... but I don't understand what you are asking here.


*> 3. silent timeout possibility?*

No.


My gut says this operation sounds inherently racey, meaning the behaviour
you see is actually expected under concurrent load and that instead the
code needs to handle the race condition. I'm saying that without actually
seeing the code and understanding the components that make up the primary
key (if any of them are computed in some way) but that is what I suspect is
going on here.


Cheers, Rob.

**Comment by jphui** [comment] 2023-05-31 20:08
General DB info:
- MySQL 8
- Isolation level: Transaction (default setting?)
- Replication lag: we are only hitting the primary node

> Race conditions

We've explored this extensively but two reasons exist that dissuade us from thinking that this is related to race conditions

1. There is a timestamp that marks when the record was introduced into the DB (column `D`). We have high trust in this timestamp and the time gap between them is on the order of days. Here is an example:

| A | B | C | D |
| - | - | - | - |
| Bob | Cat | 0 | 2023-05-25 04:30:52 |
| Bob | Cat | 0 | 2023-05-24 04:27:32 |
| Bob | Cat | 1 | 2023-05-21 04:35:15 |
| Bob | Cat | 2 | 2023-05-14 04:38:24 |

In this example, the first two rows are considered "duplicates" because they have the same `{ A, B, C }`. This happened because at `2023-05-25 04:30:52` , Ebean performed a `.find()` and failed to retrieve the second row marked `2023-05-24 04:27:32`. This prompts an insertion.

Unfortunately, we CANNOT change the DB's Primary Key to exclude `D` to handle duplicity at the DB level ... it must remain as all 4 attributes.

2. We've introduced logging alongside the calls and returns through Ebean and have confirmed that the records being requested have existed in the DB for a long time (some months before).

- The only case that might induce a race condition is that it's possible that **two requests to retrieve the record come at the same time** ... but is there a such thing as a READ-READ case that would cause Ebean to return null?

> Key modeling mismatch

For concision:
- Ebean model PK: `{ A, B, C }`
- DB PK: `{ A, B, C, D }`

The details of attributes A, B, C, D are here: https://github.com/linkedin/datahub-gma/blob/master/dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanMetadataAspect.java#L52

In effect, the DB's Primary Key is the same primary key as the one modeled there but with the `createdOn` field included as well. **We work under the assumption that Ebean's modeling of the DB as it relates to keys and uniqueness shouldn't affect the ability of its queries to properly retrieve records**. _After all, it is able to do so correctly about 95% of the time._

We are working on a sanity check bypassing Ebean by using the underlying JDBC to perform a query to see if a lower level operation will yield any differing results since there is no need to convert models, etc.

**Comment by rbygrave** [comment] 2023-05-31 20:41
MySQL in the past was know to truncate timestamps ... but it does not sound like that is an issue here if that isn't part of the query?

What is the java code that does the find?  What is the SQL that the ebean query produces?

**Comment by jphui** [comment] 2023-05-31 20:54
> Java Code

https://github.com/linkedin/datahub-gma/blob/07be8aa7ecbdea3d150b20b59d39467f173402bf/dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java#L482

> Produced SQL

```
select t0.urn, t0.aspect, t0.version, t0.createdOn, t0.createdBy, t0.createdFor from metadata_aspect t0 
where urn = ? and aspect = ? and version = ? 
order by t0.createdOn desc
```
( the bindings don't show up with `.getGeneratedSql()` , our most recent commit should put the call _after_ the query execution in hopes the bindings will show up )

**Comment by jphui** [comment] 2023-05-31 20:57
We believe the JDBC sanity check will be very telling to decide whether this is a Ebean or MySQL issue. This thread isn't meant to be a comprehensive investigation but more to see what Ebean-related limitations / known issues exist that might be the root cause.

If based on the information provided here, there is confidence that it is * not * an Ebean issue, then I would be satisfied to closing the thread :)

**Comment by rbygrave** [comment] 2023-06-01 06:40
> but is there a such thing as a READ-READ case that would cause Ebean to return null?

No.

This is the query in question right?  The issue is that this returns an empty list right?

```java
    if (_findMethodology == FindMethodology.QUERY_BUILDER) {
      query = _server.find(EbeanMetadataAspect.class)
        .where()
        .eq(URN_COLUMN, urn.toString())
        .eq(ASPECT_COLUMN, aspectName)
        .eq(VERSION_COLUMN, 0L)
        .orderBy()
        .desc(CREATED_ON_COLUMN);
    }

    results = query.findList();
```

> Key modeling mismatch

The primary key isn't really relevant with the query above. It isn't a "find by id" per se.


For this query the JDBC types being bound are String, String and long - so nothing odd or interesting with these types (like truncation of precision on timestamp etc) and nothing interesting regarding timezone.

The only thing that jumps out at me is character encoding. Is there something interesting with urn.toString()?  Is there any whitespace or special characters in play etc.

**Comment by jphui** [comment] 2023-06-01 23:46
> The issue is that this returns an empty list right?

Yep. Even when in the DB, it's clear there is an existing record.

> character encoding

The urns definitely do not have whitespace, but they make use of `(` , `)` , `-` , `,` , `_` , `:` . It is worth noting that almost ALL urn's have these characters, though.

That being said, I notice that in the `.getGeneratedSql()` , there are no quotes around the string fields... should these be added to ensure correct parsing?

- ie. `urn = ?` ==> `urn = '?'` or such

**Comment by jphui** [comment] 2023-06-05 22:18
Hello, @rbygrave :) We're currently investigating your suggestion of `character encoding` as a possible culprit of inconsistency.

In the meantime, do you have any insight into the influence of the `@Index` annotation on how Ebean processes `.find...()` calls that take a `bean.class` as an argument? In other words, if `@Index` is set on fields that are actually NOT indexed fields -- or more importantly vice versa, where `@Index` is not set on fields that ARE indexed -- is the behavior defined for Ebean?

**Comment by rob-bygrave** [comment] 2023-06-06 02:14
> @Index

Has no impact on ebean `.find...()`.

Yes, there is a relationship between `@Id` and Primary Key and "Find by Id" in terms of mapping, but technically ebean does not know about indexes at runtime and indexes have no impact on ebean `.find...()`.

`@Index` is used to control DDL that ebean would generate.  For ebean `.find...()` it really does not know about or care about actual database indexes per se. 


> there are no quotes around the string fields

As expected, this is how JDBC works. Those `?` are placeholders and the underlying JDBC PreparedStatement has type specific binding methods like `preparedStatement.setString(...)`.

**Comment by jphui** [comment] 2023-06-06 17:39
Thanks for the insight!

I also noted that overriding `.equals()` and/or `.hashCode()` is explicitly discouraged. In our implementation we've overridden them for internal use cases but am wondering if it has now having a side effect on `.find...()` , any confounding interactions that you know of?

**Comment by rob-bygrave** [comment] 2023-06-06 21:15
> overriding .equals() and/or .hashCode() is explicitly discouraged.

It's more that it's harder to implement than it looks (due to entities naturally mutating and use of generated keys) and often it is implemented incorrectly e.g. with a hashCode() that changes value. Plus there is some really bad advice out there on the internet wrt equals/hashCode and JPA. 

 
> having a side effect on `.find...()`

No it does not - Ebean doesn't require or use the equals/hashCode on entities so you can implement it however you like. 

Notes: Some ORMs like Hibernate and JPA implementations in general, actually require a equals/hashCode implementation and use it to manage the entities in their persistence context but this is _NOT_ the case for Ebean.

**Comment by yangyangv2** [comment] 2023-07-24 17:52
To give a bit more context, below are the logic we're using

```
    final PrimaryKey key = new PrimaryKey(id, name, 0L);
    MyRecord record = _server.find(MyRecord.class, key);
```

the `_server.find()` sometimes return `null`, even the data is in the database.

**Comment by rbygrave** [comment] 2023-07-24 19:51
>  when .find() returns null, besides the query doesn't find any record in the database, can there be other reasons? such as processing or communication error on EBean implementation?

No.

> the _server.find() sometimes return null, even the data is in the database.

Are you able to produce a failing test case?

**Comment by rbygrave** [comment] 2023-07-24 19:53
> The mysql did receive the the request and send response, but the eBean's .find() method does not return consistently.

How do you know this?  What are you doing to confirm that is the case?

**Comment by yangyangv2** [comment] 2023-07-24 19:59
we see this issue everyday in our daily pipeline. a few questions

1) what are the other reasons find() return null? if it's an error, any reason it doesn't throw exception.
2) is there an alternative API can "reliably" tell if the query doesn't get any data from the database.

The way we confirm this is by calling the find() again when it returns null. We confirmed from the DB that two identical SQLs are received one after another (within 10 ms). And from the EBean client side, the log captured the 2nd call get the correct value returned.

No exception was thrown during this process.

**Comment by rob-bygrave** [comment] 2023-07-24 21:15
> is there an alternative API can "reliably" tell if the query doesn't get any data from the database.

Use JDBC. Obtain the `java.sql.Connection` from the Ebean transaction or obtain the `DataSource` from `io.ebean.Database`.

**Comment by yangyangv2** [comment] 2023-07-25 12:37
Thanks @rPraml, we haven't explicitly enable the caching. Is there a quick way to check whether the caching is enabled?

The missing records are from 1 day old to up to 6 months (when we launched the service). We only see this issue in the production service, which is 5M SQL calls per hour or 100K SQL calls per instance/hour. We never reproduce it manually or in our staging environment.

How much logs it may reproduce if I enable "io.ebean.SQL/SUM/TXN", we have around 600G available disk space in our service host.

**Comment by yangyangv2** [comment] 2023-07-25 12:42
@rob-bygrave , we used to try with the following code and ran into closed transaction error (this call is made in a transaction and the transaction is managed by a retry in the upstream caller)

`_server.getPluginApi().getDataSource().getConnection();`

what should be the recommended way of using Connection from EBean? Leaving the Connection, Statement unclosed during the execution? Is there any code example?

**Comment by rbygrave** [comment] 2024-02-10 00:32
No updates here, I'll close this for now.

**Closed by rbygrave** 2024-02-10 00:32 UTC
