### ISSUE TITLE
Wrong query when using @SoftDelete

### ISSUE THREAD

**Issue by IvanAR** [ebean-orm/ebean#965] opened 2017-02-08 16:55 UTC
## Expected behavior
Execute the query without errors and return.

## Actual behavior
Query is being built with wrong syntax putting the soft delete AND together with property

### Steps to reproduce
Execute the followint test  
https://github.com/IvanAR/example-java8/blob/master/src/test/java/org/example/domain/BetweenOrderDateTest.java

```java
Ebean.find(Order.class).where().betweenProperties("orderDate", "shipDate", new LocalDate[]{}).findList();
```

```console
javax.persistence.PersistenceException: Query threw SQLException:Syntax error in SQL statement "SELECT T0.ID, T0.STATUS, T0.ORDER_DATE, T0.SHIP_DATE, T0.VERSION, T0.WHEN_CREATED, T0.WHEN_UPDATED, T0.DELETED, T0.CUSTOMER_ID, T0.SHIPPING_ADDRESS_ID FROM O_ORDER T0 WHERE  ?  BETWEEN T0.ORDER_DATE AND T0.SHIP_DATEAND T0[*].DELETED = FALSE "; SQL statement:
select t0.id, t0.status, t0.order_date, t0.ship_date, t0.version, t0.when_created, t0.when_updated, t0.deleted, t0.customer_id, t0.shipping_address_id from o_order t0 where  ?  between t0.order_date and t0.ship_dateand t0.deleted = false [42000-191] 
Bind values:[null] 
Query was:
select t0.id, t0.status, t0.order_date, t0.ship_date, t0.version, t0.when_created, t0.when_updated, t0.deleted, t0.customer_id, t0.shipping_address_id from o_order t0 where  ?  between t0.order_date and t0.ship_dateand t0.deleted = false 



	at io.ebeaninternal.server.query.CQuery.createPersistenceException(CQuery.java:680)
	at io.ebeaninternal.server.query.CQuery.createPersistenceException(CQuery.java:660)
	at io.ebeaninternal.server.query.CQueryEngine.findMany(CQueryEngine.java:343)
	at io.ebeaninternal.server.query.DefaultOrmQueryEngine.findMany(DefaultOrmQueryEngine.java:105)
	at io.ebeaninternal.server.core.OrmQueryRequest.findList(OrmQueryRequest.java:341)
	at io.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1413)
	at io.ebeaninternal.server.querydefn.DefaultOrmQuery.findList(DefaultOrmQuery.java:1202)
	at io.ebeaninternal.server.expression.DefaultExpressionList.findList(DefaultExpressionList.java:394)
	at org.example.domain.BetweenTest.betweenProperties(BetweenTest.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by rbygrave** [comment] 2017-02-09 10:46
This is a duplicate of https://github.com/ebean-orm/ebean/issues/960

Will be fixed (in 10.1.6).

**Closed by rbygrave** 2017-02-09 10:46 UTC
Labels: bug, duplicate
