### ISSUE TITLE
builtin-extra-ddl.xml references invalid location and causes an exception with Java 8

### ISSUE THREAD

**Issue by robnielsen** [ebean-orm/ebean#1749] opened 2019-07-03 12:13 UTC
/io/ebeaninternal/dbmigration/builtin-extra-ddl.xml has the following:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<extra-ddl xmlns="http://ebean-orm.github.io/xml/ns/extraddl">
...
```

This is causing an exception:
```
Caused by: java.lang.RuntimeException: javax.xml.bind.UnmarshalException: unexpected element (uri:"http://ebean-orm.github.io/xml/ns/extraddl", local:"extra-ddl"). Expected elements are <{}ddl-script>,<{}extra-ddl>
	at io.ebeaninternal.extraddl.model.ExtraDdlXmlReader.read(ExtraDdlXmlReader.java:147)
	at io.ebeaninternal.extraddl.model.ExtraDdlXmlReader.read(ExtraDdlXmlReader.java:130)
	at io.ebeaninternal.extraddl.model.ExtraDdlXmlReader.readBuiltin(ExtraDdlXmlReader.java:103)
	at io.ebeaninternal.dbmigration.model.CurrentModel.getCreateDdl(CurrentModel.java:137)
	at io.ebeaninternal.dbmigration.DdlGenerator.generateCreateAllDdl(DdlGenerator.java:301)
	at io.ebeaninternal.dbmigration.DdlGenerator.writeCreate(DdlGenerator.java:282)
	at io.ebeaninternal.dbmigration.DdlGenerator.generateDdl(DdlGenerator.java:91)
	at io.ebeaninternal.dbmigration.DdlGenerator.execute(DdlGenerator.java:77)
	at io.ebeaninternal.server.core.DefaultServer.executePlugins(DefaultServer.java:336)
	at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:131)
	at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:69)
	at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:35)
	at io.ebean.EbeanServerFactory.create(EbeanServerFactory.java:58)
	at io.ebean.Ebean$ServerManager.getWithCreate(Ebean.java:126)
	at io.ebean.Ebean$ServerManager.<init>(Ebean.java:75)
	... 35 more
Caused by: javax.xml.bind.UnmarshalException: unexpected element (uri:"http://ebean-orm.github.io/xml/ns/extraddl", local:"extra-ddl"). Expected elements are <{}ddl-script>,<{}extra-ddl>
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.handleEvent(UnmarshallingContext.java:726)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:247)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:242)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.reportUnexpectedChildElement(Loader.java:109)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext$DefaultRootLoader.childElement(UnmarshallingContext.java:1131)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:556)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.startElement(UnmarshallingContext.java:538)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.SAXConnector.startElement(SAXConnector.java:153)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl$NSContentDriver.scanRootElementHook(XMLNSDocumentScannerImpl.java:613)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3132)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:852)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:243)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:214)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:157)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:204)
	at io.ebeaninternal.extraddl.model.ExtraDdlXmlReader.read(ExtraDdlXmlReader.java:144)
	... 49 more
```

When accessing http://ebean-orm.github.io/xml/ns/extraddl from a browser a 404 is thrown.  Changing the file to:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<extra-ddl>
...
```
The exception goes away. Accessing http://ebean-orm.github.io/xml/ns/extraddl should not throw a 404.

**Comment by robnielsen** [comment] 2019-07-03 12:26
This has been discussed at https://groups.google.com/forum/#!topic/ebean/oBOqc72UWik

**Comment by rbygrave** [comment] 2019-07-08 07:08
Hi @robnielsen  Note that at this point we still do not have the steps to reproduce this. Can you produce a project that produces this exception / reproduces the problem?  Are you seeing the problem when building or running?  If running how is it being run?

There is the minimal project ... maybe create a fork of that that reproduces the problem?
https://github.com/ebean-orm-examples/example-minimal

Thanks

**Comment by rbygrave** [comment] 2019-07-09 23:54
@robnielsen  are you able to provide more information in order to reproduce?  
- Are you using maven - can you provide a maven dependency tree?
- Provide the version of JDK being used?
- Does this appear when running in IDE only?  Which IDE?

Thanks

**Comment by rbygrave** [comment] 2019-07-16 22:40
Hi @robnielsen  ... I haven't been able to reproduce.  Can you give me any clues?  Running in eclipse IDE?  Has anyone else hit this issue? Thanks.

**Comment by rbygrave** [comment] 2019-07-17 09:29
I am beginning to think this is a classpath issue and that there are multiple JAXB implementations in the classpath.  A `mvn dependency:tree` might show another JAXB implementation in the classpath (other than the one in JDK8 itself)?

If you could check that @robnielsen that would be great.  

Again note that I am unable to reproduce.  The 404 on the http location shouldn't matter - it has never been there basically and the xsd in the ebean jar should instead be found by JAXB.

Thanks, Rob.

**Comment by rbygrave** [comment] 2019-07-21 04:34
I'll close this for no as we haven't reproduced and we need further information.

If someone comes back with more information on how to reproduce we can reopen, reproduce and progress it.

**Closed by rbygrave** 2019-07-21 04:34 UTC
Labels: Waiting for more information
