### ISSUE TITLE
Failed to create EbeanServer with @Embeddable class that relation to another entity

### ISSUE THREAD

**Issue by vkuzel** [ebean-orm/ebean#1385] opened 2018-05-23 14:20 UTC
## Expected behaviour

Ebean should be able to handle entity structure described in the [example 2 of the `@Embeddable` annotation documentation](https://github.com/ebean-orm/javax-persistence-api/blob/master/src/main/java/javax/persistence/Embeddable.java).

## Actual behaviour

EbeanServer instantiation fails with an error message _Error reading annotations for embeddabletest.EmbeddableTest$PhoneNumber_.

### Steps to reproduce

Add classes to ServerConfig and call `EbeanServerFactory.create()`.

```java
public class EmbeddableTest {
    public static void main(String[] args) {
        ServerConfig config = new ServerConfig();
        config.loadFromProperties();
        config.addClass(PhoneServiceProvider.class);
        config.addClass(PhoneNumber.class);
        EbeanServerFactory.create(config);
    }

    @Embeddable
    public static class PhoneNumber {
        private String areaCode;
        private String localNumber;
        @ManyToOne private PhoneServiceProvider provider;
        // Getters and setters omitted
    }

    @Entity
    public static class PhoneServiceProvider {
        @Id private String name;
        // Getters and setters omitted
    }
}
```

### Problem cause

When embeddable class is deployed by `BeanDescriptionManager.readEntityDeploymentInitial()` it tries to do lookup for `BeanTable` of `PhoneServiceProvider.class` in `BeanDescriptorManager.beanTableMap`. But, the map is populated [**after** the lookup, by `BeanDescriptorManager.readEntityBeanTable()`](https://github.com/ebean-orm/ebean/blob/42d83705b79e31f24d2f6facd9f37ec06a23f746/src/main/java/io/ebeaninternal/server/deploy/BeanDescriptorManager.java#L367).

Here is the stack-trace of `BeanTable` lookup:

* **beanTable:193, AnnotationAssocOnes (io.ebeaninternal.server.deploy.parse)** :arrow_left: exception is thrown.
* readManyToOne:204, AnnotationAssocOnes (io.ebeaninternal.server.deploy.parse)
* readAssocOne:66, AnnotationAssocOnes (io.ebeaninternal.server.deploy.parse)
* parse:57, AnnotationAssocOnes (io.ebeaninternal.server.deploy.parse)
* readAssociations:49, ReadAnnotations (io.ebeaninternal.server.deploy.parse)
* readDeployAssociations:1313, BeanDescriptorManager (io.ebeaninternal.server.deploy)
* readEntityDeploymentInitial:719, BeanDescriptorManager (io.ebeaninternal.server.deploy)
* **deploy:364, BeanDescriptorManager (io.ebeaninternal.server.deploy)** :arrow_left: interesting method.
* <init>:163, InternalConfiguration (io.ebeaninternal.server.core)
* createServer:139, DefaultContainer (io.ebeaninternal.server.core)
* createServer:45, DefaultContainer (io.ebeaninternal.server.core)
* createInternal:109, EbeanServerFactory (io.ebean)
* create:70, EbeanServerFactory (io.ebean)
* main:18, EmbeddableTest (embeddabletest)

**Comment by rbygrave** [comment] 2018-05-24 00:44
This is a duplicate of https://github.com/ebean-orm/ebean/issues/52

**Comment by rbygrave** [comment] 2018-05-28 11:48
I presume you are happy for us to close this as a duplicate.  If not then update this ticket etc.

Cheers, Rob.

**Closed by rbygrave** 2018-05-28 11:48 UTC
Labels: duplicate
