### ISSUE TITLE
Interrupted getting connection from pool java.lang.InterruptedException

### ISSUE THREAD

**Issue by greenlaw110** [ebean-orm/ebean#620] opened 2016-03-25 00:29 UTC
Ebean version: 7.3.1
Ebean datasource version: 1.1.1

Reproduce steps:
1. create an ebean server and use it, all good so far
2. shutdown the ebean server with shutdownDatasource set to true
3. create an new ebean server. You get the error stack:

```
javax.persistence.PersistenceException: java.sql.SQLException: Interrupted getting connection from pool java.lang.InterruptedException
    at com.avaje.ebeaninternal.server.core.DefaultContainer.checkDataSource(DefaultContainer.java:361)
    at com.avaje.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:102)
    at com.avaje.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:41)
    at com.avaje.ebean.EbeanServerFactory.createInternal(EbeanServerFactory.java:108)
    at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:67)
    at act.db.ebean.EbeanService$2.on(EbeanService.java:61)
    at act.event.EventBus.callOn(EventBus.java:134)
    at act.event.EventBus.callOn(EventBus.java:155)
    at act.event.EventBus.callOn(EventBus.java:171)
    at act.event.EventBus.emit(EventBus.java:189)
    at act.event.EventBus.emit(EventBus.java:180)
    at act.app.App.emit(App.java:504)
    at act.app.App.refresh(App.java:273)
    at act.app.CliSession.run(CliSession.java:90)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: Interrupted getting connection from pool java.lang.InterruptedException
    at org.avaje.datasource.pool.PooledConnectionQueue.getPooledConnection(PooledConnectionQueue.java:277)
    at org.avaje.datasource.pool.ConnectionPool.getPooledConnection(ConnectionPool.java:712)
    at org.avaje.datasource.pool.ConnectionPool.getConnection(ConnectionPool.java:700)
    at com.avaje.ebeaninternal.server.core.DefaultContainer.checkDataSource(DefaultContainer.java:351)
    ... 20 more
```

**Comment by rbygrave** [comment] 2016-03-25 00:43
What version of Ebean are you using?

I see act package in the stack trace.  Have you reproduced in a stand alone
test?

**Comment by rbygrave** [comment] 2016-03-25 00:55
So if I do:

```java
ServerConfig config = new ServerConfig();
config.setName("h2");
...
EbeanServer ebeanServer = EbeanServerFactory.create(config);

ebeanServer.shutdown(true, false); // shutdown DataSource = true

// create anther instance
EbeanServer anotherServer = EbeanServerFactory.create(config);

```
I get a different stack trace.  I get:

javax.persistence.PersistenceException: java.sql.SQLException: Trying to access the Connection Pool when it is shutting down

	at com.avaje.ebeaninternal.server.core.DefaultContainer.checkDataSource(DefaultContainer.java:361)
	at com.avaje.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:102)
	at com.avaje.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:41)
	at com.avaje.ebean.EbeanServerFactory.createInternal(EbeanServerFactory.java:108)
	at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:67)
	at com.avaje.ebean.EbeanServerFactory_ServerConfigStart_Test.test(EbeanServerFactory_ServerConfigStart_Test.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.sql.SQLException: Trying to access the Connection Pool when it is shutting down
	at org.avaje.datasource.pool.PooledConnectionQueue._getPooledConnection(PooledConnectionQueue.java:297)
	at org.avaje.datasource.pool.PooledConnectionQueue.getPooledConnection(PooledConnectionQueue.java:271)
	at org.avaje.datasource.pool.ConnectionPool.getPooledConnection(ConnectionPool.java:712)
	at org.avaje.datasource.pool.ConnectionPool.getConnection(ConnectionPool.java:700)
	at com.avaje.ebeaninternal.server.core.DefaultContainer.checkDataSource(DefaultContainer.java:351)
	... 40 more

**Comment by rbygrave** [comment] 2016-03-25 01:00
If you don't shutdown the server then the error does not occur.

```java
// do not shutdown the datasource
ebeanServer.shutdown(false, false);
```

... and that is fine because the DataSource from the first EbeanServer instance is left running.

Alternatively if I set DataSource to null so:

```java
// shutdown the dataSource
ebeanServer.shutdown(true, false);
// set it to null on ServerConfig forcing Ebean to create a new DataSource
config.setDataSource(null);
```

... so this is also fine.

**Comment by rbygrave** [comment] 2016-03-25 01:03
Right now I believe that the "fix" for this is that when you shutdown an EbeanServer instance AND datasource shutdown is TRUE ... then Ebean should implicitly set the DataSource to null on the ServerConfig.

That would fix this issue and also allow people to re-user a DataSource between "a EbeanServer restart".

**Comment by rbygrave** [comment] 2016-03-25 01:11
Your stack trace is different from mine.  

**Can you confirm that those workarounds result in it 'working'?**

1) config.setDataSource(**null**);
2)  ebeanServer.shutdown(**false**, false);

If these work then I'm happy that I'm seeing the exact same issue and that the proposed "fix" (implicitly setting the DataSource to null on the serverConfig) actually fixes the problem.

**Comment by rbygrave** [comment] 2016-03-25 01:14
Alternatively you could check if your stack trace includes the root cause.  I'm expecting to see:

"java.sql.SQLException: Trying to access the Connection Pool when it is shutting down"

**Comment by greenlaw110** [comment] 2016-03-25 01:25
Hey @rbygrave  thanks for quick response!

Let me give you some background:

So act MVC framework (http://github.com/actframework) is designed to support hot reloading of app classes so that once user changed their code while the app is running in dev mode, act will obsolete the existing application class loader and reload all services including [ebean service](https://github.com/actframework/act-ebean). That means both server config and ebean server will be an new instance after server restart. So `config.setDataSource(null)` won't help. And I have to let the old ebean server to shutdown datasource as well, because the new ebean server will create an new datasource anyway.

I've never encountered the `Trying to access the Connection Pool when it is shutting down` error, always failed with `Interrupted getting connection from pool java.lang.InterruptedException`

**Comment by greenlaw110** [comment] 2016-03-25 01:28
In your code:

```java
ServerConfig config = new ServerConfig();
config.setName("h2");
...
EbeanServer ebeanServer = EbeanServerFactory.create(config);

ebeanServer.shutdown(true, false); // shutdown DataSource = true

// create anther instance
EbeanServer anotherServer = EbeanServerFactory.create(config);
```

Between `ebeanServer.shutdown(true, false)` and create another instance. Can you let the thread sleep for some time and see if you can reproduce the interrupted exception

**Comment by rbygrave** [comment] 2016-03-25 01:29
I'll try ...

**Comment by rbygrave** [comment] 2016-03-25 01:32
No, that does not reproduce (and you'd expect that) because the sleep is just fine.

**Comment by rbygrave** [comment] 2016-03-25 01:33
You need to show me the code in:  act.db.ebean.EbeanService$2.on(EbeanService.java:61)

**Comment by rbygrave** [comment] 2016-03-25 01:35
Well, I'm looking at:
https://github.com/actframework/act-ebean/blob/master/src/main/java/act/db/ebean/EbeanService.java

To me it looks like the shudown and the create can happen on different threads.

**Comment by greenlaw110** [comment] 2016-03-25 01:41
May or may not. Take a look at the following error stack:

```
javax.persistence.PersistenceException: java.sql.SQLException: Interrupted getting connection from pool java.lang.InterruptedException
	at com.avaje.ebeaninternal.server.core.DefaultContainer.checkDataSource(DefaultContainer.java:361)
	at com.avaje.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:102)
	at com.avaje.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:41)
	at com.avaje.ebean.EbeanServerFactory.createInternal(EbeanServerFactory.java:108)
	at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:67)
	at act.db.ebean.EbeanService$2.on(EbeanService.java:61)
	at act.event.EventBus.callOn(EventBus.java:134)
	at act.event.EventBus.callOn(EventBus.java:155)
	at act.event.EventBus.callOn(EventBus.java:171)
	at act.event.EventBus.emit(EventBus.java:189)
	at act.event.EventBus.emit(EventBus.java:180)
	at act.app.App.emit(App.java:504)
	at act.app.App.refresh(App.java:273)
	at act.app.CliSession.run(CliSession.java:90)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: Interrupted getting connection from pool java.lang.InterruptedException
	at org.avaje.datasource.pool.PooledConnectionQueue.getPooledConnection(PooledConnectionQueue.java:277)
	at org.avaje.datasource.pool.ConnectionPool.getPooledConnection(ConnectionPool.java:712)
	at org.avaje.datasource.pool.ConnectionPool.getConnection(ConnectionPool.java:700)
	at com.avaje.ebeaninternal.server.core.DefaultContainer.checkDataSource(DefaultContainer.java:351)
	... 20 more
```

What happens is when developer changed the code the App will [refresh](https://github.com/actframework/actframework/blob/master/src/main/java/act/app/App.java#L220), it will first shutdown all services, and then reboot itself, load all services, load all classes.These are all happen in one thread. Even if shutdown and create ebean happened in two different thread, they are unlikely to happen concurrently. Is there a problem with that?

**Comment by rbygrave** [comment] 2016-03-25 01:49
To me it looks like somthing (some thread) is interrupting the thread that is creating the EbeanServer instance.

I see that ServerConfig is not a shared instance so right now I have not got a test case that reproduces this problem.

Can the threads/events on the 'event bus' be interrupted/cancelled (it looks like it) and what does that?

**Comment by rbygrave** [comment] 2016-03-25 01:51
> Even if shutdown and create ebean happened in two different thread, they are unlikely to happen concurrently. Is there a problem with that?

No I don't think that is a problem (as ServerConfig is not a shared instance between the ebeanServer instances).

**Comment by greenlaw110** [comment] 2016-03-25 02:00
> Can the threads/events on the 'event bus' be interrupted/cancelled (it looks like it) and what does that?

No, not at all. It's within an event handler when app loaded all applications. Nothing will interrupt or cancel that thread
![image](https://cloud.githubusercontent.com/assets/216930/14036071/6e6fcdb4-f289-11e5-8bb4-031d3ddc3a97.png)

**Comment by rbygrave** [comment] 2016-03-25 02:05
Ok, well PooledConnectionQueue line 277:

```java
    } catch (InterruptedException e) {
      String msg = "Interrupted getting connection from pool " + e;
      throw new SQLException(msg);
    }
```

So to me InterruptedException is being thrown.  Unfortunately the cause expection is just "toString()" there meaning we are losing the root InterruptedException in our stack trace.

So I can change that to   throw new SQLException(msg, e); ... but you could perhaps put a breakpoint there and run it and see what the root cause is.

**Comment by greenlaw110** [comment] 2016-03-25 02:07
doing that now...

**Comment by greenlaw110** [comment] 2016-03-25 02:09
Found this:

```
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1220)
	at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:335)
	at org.avaje.datasource.pool.PooledConnectionQueue._getPooledConnection(PooledConnectionQueue.java:294)
	at org.avaje.datasource.pool.PooledConnectionQueue.getPooledConnection(PooledConnectionQueue.java:271)
	at org.avaje.datasource.pool.ConnectionPool.getPooledConnection(ConnectionPool.java:712)
	at org.avaje.datasource.pool.ConnectionPool.getConnection(ConnectionPool.java:700)
	at com.avaje.ebeaninternal.server.core.DefaultContainer.checkDataSource(DefaultContainer.java:351)
	at com.avaje.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:102)
	at com.avaje.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:41)
	at com.avaje.ebean.EbeanServerFactory.createInternal(EbeanServerFactory.java:108)
	at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:67)
	at act.db.ebean.EbeanService$2.on(EbeanService.java:61)
	at act.event.EventBus.callOn(EventBus.java:134)
	at act.event.EventBus.callOn(EventBus.java:155)
	at act.event.EventBus.callOn(EventBus.java:171)
	at act.event.EventBus.emit(EventBus.java:189)
	at act.event.EventBus.emit(EventBus.java:180)
	at act.app.App.emit(App.java:504)
	at act.app.App.refresh(App.java:273)
	at act.app.CliSession.run(CliSession.java:90)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by greenlaw110** [comment] 2016-03-25 02:14
Having lunch now. Will keep looking at it in 1 hour...

**Comment by rbygrave** [comment] 2016-03-25 03:23
Note I logged #621 to address the:

"java.sql.SQLException: Trying to access the Connection Pool when it is shutting down"

**Comment by greenlaw110** [comment] 2016-03-25 03:49
Hi I think it's my problem. the current thread has been interrupted during application refresh actually.

**Comment by rbygrave** [comment] 2016-03-25 03:51
Yup cool.  That was kind of fun to look at though :)

**Comment by greenlaw110** [comment] 2016-03-25 06:08
Yep! It's very enjoyable to co-work with someone like you. BTW ebean is awesome! I love it :+1:

**Comment by greenlaw110** [comment] 2017-05-28 00:22
It happens again intermittently after fixed a bug that ebean is not shutdown during app refresh. The full error stack:

```
at act.db.sql.SqlDbService$1.run(SqlDbService.java:53)
at act.job._Job$2.apply(_Job.java:294)
at act.job._Job.doJob(_Job.java:256)
at act.job._Job.run(_Job.java:196)
at act.job._Job$LockableJobList.runSubJobs(_Job.java:75)
at act.job._Job.runPrecedenceJobs(_Job.java:271)
at act.job._Job.run(_Job.java:191)
at act.job.AppJobManager$_AppEventListener.on(AppJobManager.java:313)
at act.event.EventBus.callOn(EventBus.java:230)
at act.event.EventBus.callOn(EventBus.java:254)
at act.event.EventBus.callOn(EventBus.java:275)
at act.event.EventBus.emit(EventBus.java:296)
at act.event.EventBus.emit(EventBus.java:284)
at act.app.App.emit(App.java:846)
at act.app.App.refresh(App.java:593)
at act.app.App.refresh(App.java:486)
at act.app.App.checkUpdates(App.java:394)
at act.xio.NetworkHandler.handle(NetworkHandler.java:101)
at act.xio.undertow.ActHttpHandler.handleRequest(ActHttpHandler.java:49)
at io.undertow.server.Connectors.executeRootHandler(Connectors.java:211)
at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:244)
at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:135)
at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:58)
at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:88)
at org.xnio.nio.WorkerThread.run(WorkerThread.java:559)
Caused by javax.persistence.PersistenceException: java.sql.SQLException: Interrupted getting connection from pool
at io.ebeaninternal.server.core.DefaultContainer.checkDataSource(DefaultContainer.java:358)
at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:111)
at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:44)
at io.ebean.EbeanServerFactory.createInternal(EbeanServerFactory.java:108)
at io.ebean.EbeanServerFactory.create(EbeanServerFactory.java:67)
at act.db.ebean2.EbeanService.createDataSource(EbeanService.java:79)
at act.db.sql.SqlDbService.initDataSource(SqlDbService.java:121)
at act.db.sql.SqlDbService.access$000(SqlDbService.java:25)
at act.db.sql.SqlDbService$1.run(SqlDbService.java:41)
at act.job._Job$2.apply(_Job.java:294)

Caused by java.sql.SQLException: Interrupted getting connection from pool
at org.avaje.datasource.pool.PooledConnectionQueue.getPooledConnection(PooledConnectionQueue.java:278)
at org.avaje.datasource.pool.ConnectionPool.getPooledConnection(ConnectionPool.java:712)
at org.avaje.datasource.pool.ConnectionPool.getConnection(ConnectionPool.java:700)
at io.ebeaninternal.server.core.DefaultContainer.checkDataSource(DefaultContainer.java:351)
at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:111)

Caused by java.lang.InterruptedException
at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1220)
at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:335)
at org.avaje.datasource.pool.PooledConnectionQueue._getPooledConnection(PooledConnectionQueue.java:295)
at org.avaje.datasource.pool.PooledConnectionQueue.getPooledConnection(PooledConnectionQueue.java:271)
at org.avaje.datasource.pool.ConnectionPool.getPooledConnection(ConnectionPool.java:712)
```

**Comment by rbygrave** [comment] 2017-08-31 09:36
I'll close this, reopen with a new issue if required etc.

**Closed by rbygrave** 2017-08-31 09:36 UTC
Labels: invalid
